# Bloc 11 — Privacy, Anonymization & Algorithmic Fairness
## Confidentialité optionnelle, anonymisation et équité algorithmique

In [115]:
from pathlib import Path

import joblib
import numpy as np
import pandas as pd


# ==========================================
# PROJECT PATHS
# ==========================================

PROJECT_DIR = Path(
    r"C:\Users\thiba\OneDrive\Bureau\Projet energie"
)

DATA_DIR = (
    PROJECT_DIR
    / "data_processed"
)

MODEL_DIR = (
    PROJECT_DIR
    / "models"
)


DATA_DIR.mkdir(
    parents=True,
    exist_ok=True
)

MODEL_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ==========================================
# RANDOM STATE
# ==========================================

RANDOM_STATE = 42

rng = np.random.default_rng(
    RANDOM_STATE
)


print(
    "Projet :",
    PROJECT_DIR
)

Projet : C:\Users\thiba\OneDrive\Bureau\Projet energie

In [116]:
# ==========================================
# BLOCK 11 CONFIGURATION
# ==========================================

PRIVACY_ENABLED = False

FAIRNESS_ENABLED = True

USE_SYNTHETIC_SANDBOX = True

RUN_PRIVACY_LAB = True


print(
    "Privacy :",
    "ON"
    if PRIVACY_ENABLED
    else "OFF"
)

print(
    "Fairness :",
    "ON"
    if FAIRNESS_ENABLED
    else "OFF"
)

print(
    "Synthetic sandbox :",
    "ON"
    if USE_SYNTHETIC_SANDBOX
    else "OFF"
)

print(
    "Privacy lab :",
    "ON"
    if RUN_PRIVACY_LAB
    else "OFF"
)

Privacy : OFF
Fairness : ON
Synthetic sandbox : ON
Privacy lab : ON

In [117]:
# ==========================================
# PRIVACY DECISION
# ==========================================

PRIVACY_MODE = (
    "experimental"
    if PRIVACY_ENABLED
    else "disabled_public_data"
)


PRIVACY_REASON = (
    "Le pipeline énergétique principal exploite "
    "des données publiques et agrégées. "
    "Aucune protection différentielle n'est "
    "appliquée par défaut."
)


print(
    "Privacy mode :",
    PRIVACY_MODE
)

print(
    "\nRaison :"
)

print(
    PRIVACY_REASON
)

Privacy mode : disabled_public_data

Raison :
Le pipeline énergétique principal exploite des données publiques et agrégées. Aucune protection différentielle n'est appliquée par défaut.

### Threat Model

Deux situations sont distinguées dans le projet.

#### Pipeline énergétique principal

Les données utilisées dans le projet sont publiques et agrégées.

Le système ne manipule donc pas directement de données individuelles
de foyers ou d'utilisateurs.

Dans ce contexte :

$$
\boxed{\text{Privacy} = OFF}
$$

Aucun mécanisme de confidentialité différentielle n'est appliqué au
pipeline principal.

#### Sandbox expérimental

Pour étudier les méthodes de confidentialité, un jeu de données
synthétique représentant des foyers sera construit séparément.

Chaque foyer pourra produire plusieurs observations temporelles :

$$
x_i =
(x_{i1}, x_{i2}, \ldots, x_{iT}).
$$

Dans ce scénario, l'unité de confidentialité sera :

$$
\boxed{\text{un foyer entier}}
$$

et non une seule ligne.

Deux datasets voisins pourront donc différer par l'ensemble des
observations appartenant à un foyer.

In [118]:
# ==========================================
# PRIVACY THREAT MODEL
# ==========================================

PRIVACY_UNIT = "household"

PRIVACY_LEVEL = "user-level"

PUBLIC_DATA_PIPELINE = True


privacy_context = {

    "privacy_enabled":
        PRIVACY_ENABLED,

    "privacy_mode":
        PRIVACY_MODE,

    "privacy_unit":
        PRIVACY_UNIT,

    "privacy_level":
        PRIVACY_LEVEL,

    "public_data_pipeline":
        PUBLIC_DATA_PIPELINE,

    "fairness_enabled":
        FAIRNESS_ENABLED,

    "synthetic_sandbox":
        USE_SYNTHETIC_SANDBOX,

    "uses_2026":
        False,
}


display(
    pd.Series(
        privacy_context,
        name="Block 11 configuration"
    )
)

privacy_enabled                        False
privacy_mode            disabled_public_data
privacy_unit                       household
privacy_level                     user-level
public_data_pipeline                    True
fairness_enabled                        True
synthetic_sandbox                       True
uses_2026                              False
Name: Block 11 configuration, dtype: object

### Privacy et sécurité du système

La désactivation de la confidentialité statistique ne signifie pas
que les mécanismes de sécurité sont désactivés.

Deux concepts doivent être distingués.

#### Data Privacy

La Data Privacy cherche à protéger les informations associées à des
individus présents dans un dataset.

Dans le pipeline énergétique principal :

$$
Privacy = OFF.
$$

#### System Security

La sécurité du système reste nécessaire pour protéger notamment :

- les mots de passe PostgreSQL ;
- les variables d'environnement ;
- les secrets de déploiement ;
- les accès aux services ;
- les permissions.

Les données énergétiques peuvent donc être publiques alors que les
informations permettant d'administrer le système restent privées.

In [119]:
# ==========================================
# SAVE BLOCK 11 CONFIGURATION
# ==========================================

BLOCK11_CONFIG_PATH = (
    MODEL_DIR
    / "block11_config.joblib"
)


joblib.dump(
    privacy_context,
    BLOCK11_CONFIG_PATH,
)


print(
    "Configuration sauvegardée :",
    BLOCK11_CONFIG_PATH
)

print(
    "Existe :",
    BLOCK11_CONFIG_PATH.exists()
)

Configuration sauvegardée : C:\Users\thiba\OneDrive\Bureau\Projet energie\models\block11_config.joblib
Existe : True

In [120]:
# ==========================================
# CHECK SAVED CONFIGURATION
# ==========================================

loaded_privacy_context = joblib.load(
    BLOCK11_CONFIG_PATH
)


display(
    pd.Series(
        loaded_privacy_context,
        name="Saved configuration"
    )
)

privacy_enabled                        False
privacy_mode            disabled_public_data
privacy_unit                       household
privacy_level                     user-level
public_data_pipeline                    True
fairness_enabled                        True
synthetic_sandbox                       True
uses_2026                              False
Name: Saved configuration, dtype: object

In [121]:
assert (
    loaded_privacy_context[
        "privacy_enabled"
    ]
    is False
)

assert (
    loaded_privacy_context[
        "uses_2026"
    ]
    is False
)


print(
    "Configuration vérifiée."
)

Configuration vérifiée.

In [122]:
# ==========================================
# PRIVACY STATUS
# ==========================================

def privacy_status():

    if PRIVACY_ENABLED:

        return {
            "enabled": True,
            "message": (
                "Privacy activée : "
                "les expériences de protection "
                "seront exécutées."
            ),
        }

    return {
        "enabled": False,
        "message": (
            "Privacy désactivée : "
            "aucune perturbation n'est appliquée "
            "au pipeline énergétique principal."
        ),
    }


status = privacy_status()


print(
    status["message"]
)

Privacy désactivée : aucune perturbation n'est appliquée au pipeline énergétique principal.

In [123]:
# ==========================================
# STEP 1 SUMMARY
# ==========================================

step1_summary = pd.DataFrame({

    "Component": [
        "Public energy pipeline",
        "Privacy",
        "Fairness",
        "Synthetic sandbox",
        "2026 final test",
    ],

    "Status": [
        "Enabled",
        "OFF",
        "ON",
        "ON",
        "Untouched",
    ],
})


display(
    step1_summary
)

                Component     Status
0  Public energy pipeline    Enabled
1                 Privacy        OFF
2                Fairness         ON
3       Synthetic sandbox         ON
4         2026 final test  Untouched

### Partie C — Analyse et améliorations guidées par la théorie

L'application d'un mécanisme de confidentialité doit dépendre du type
de données et du risque que l'on souhaite contrôler.

Dans le pipeline énergétique principal, les données exploitées sont
publiques et agrégées.

L'ajout de bruit de confidentialité différentielle réduirait donc
l'utilité statistique sans répondre à un besoin de protection
individuelle identifié dans le cas d'usage actuel.

On choisit donc :

$$
\boxed{Privacy_{production}=OFF}.
$$

La confidentialité reste néanmoins étudiée dans un environnement
synthétique séparé.

Dans ce scénario expérimental, plusieurs observations appartiennent au
même foyer :

$$
x_i =
(x_{i1},\ldots,x_{iT}).
$$

La future unité de confidentialité sera donc le foyer entier.

Cette distinction permettra ensuite de comparer :

$$
\text{utilité sans protection}
$$

et

$$
\text{utilité avec protection}.
$$

La sécurité du système reste indépendante de cette décision :
les mots de passe, secrets et accès PostgreSQL doivent toujours rester
protégés.

Conclusion :

La stratégie de confidentialité du Bloc 11 est maintenant définie.

La Privacy est désactivée par défaut pour le pipeline énergétique
principal, tandis qu'elle reste disponible comme module expérimental.

L'étude de l'équité reste activée et sera réalisée sur un environnement
synthétique indépendant.

La configuration est sauvegardée et aucune donnée de l'année 2026
n'est utilisée.

## Étape 2 — Création du sandbox synthétique

### Partie A — Mise en pratique

Les données RTE du projet principal sont publiques et agrégées.

Pour étudier des problématiques qui nécessitent des observations
individuelles, on construit donc un dataset entièrement synthétique
représentant des foyers.

Ce dataset n'est pas utilisé pour remplacer les données énergétiques
réelles du projet.

Il sert uniquement aux expériences :

- d'équité algorithmique ;
- d'anonymisation ;
- de confidentialité différentielle lorsque celle-ci est activée.

Chaque foyer produit 48 observations correspondant à une journée
échantillonnée toutes les 30 minutes.

In [124]:
# ==========================================
# SYNTHETIC SANDBOX PATH
# ==========================================

SYNTHETIC_PATH = (
    DATA_DIR
    / "block11_synthetic_households.joblib"
)


print(
    "Dataset synthétique :",
    SYNTHETIC_PATH
)

Dataset synthétique : C:\Users\thiba\OneDrive\Bureau\Projet energie\data_processed\block11_synthetic_households.joblib

In [125]:
# ==========================================
# SYNTHETIC DATA PARAMETERS
# ==========================================

N_HOUSEHOLDS = 1000

N_STEPS = 48

FREQUENCY = "30min"


print(
    "Nombre de foyers :",
    N_HOUSEHOLDS
)

print(
    "Observations par foyer :",
    N_STEPS
)

print(
    "Nombre total attendu :",
    N_HOUSEHOLDS * N_STEPS
)

Nombre de foyers : 1000
Observations par foyer : 48
Nombre total attendu : 48000

In [126]:
# ==========================================
# HOUSEHOLD TABLE
# ==========================================

household_ids = np.arange(
    N_HOUSEHOLDS
)


households = pd.DataFrame({

    "household_id":
        household_ids,

    "sensitive_group":
        rng.choice(
            [
                "A",
                "B",
            ],
            size=N_HOUSEHOLDS,
            p=[
                0.55,
                0.45,
            ],
        ),

    "household_size":
        rng.integers(
            1,
            6,
            size=N_HOUSEHOLDS,
        ),
})

In [127]:
# ==========================================
# HOUSEHOLD CHARACTERISTICS
# ==========================================

households[
    "dwelling_type"
] = rng.choice(
    [
        "apartment",
        "house",
    ],
    size=N_HOUSEHOLDS,
    p=[
        0.60,
        0.40,
    ],
)


households[
    "electric_heating"
] = rng.binomial(
    n=1,
    p=0.45,
    size=N_HOUSEHOLDS,
)

In [128]:
households[
    "energy_efficiency"
] = rng.choice(
    [
        "high",
        "medium",
        "low",
    ],
    size=N_HOUSEHOLDS,
    p=[
        0.25,
        0.50,
        0.25,
    ],
)

In [129]:
# ==========================================
# SYNTHETIC GROUP EFFECT
# ==========================================

group_b_mask = (
    households[
        "sensitive_group"
    ]
    == "B"
)


n_group_b = int(
    group_b_mask.sum()
)


households.loc[
    group_b_mask,
    "energy_efficiency"
] = rng.choice(
    [
        "high",
        "medium",
        "low",
    ],
    size=n_group_b,
    p=[
        0.15,
        0.45,
        0.40,
    ],
)

In [130]:
display(
    households.head()
)


print(
    "Shape households :",
    households.shape
)


display(
    households[
        "sensitive_group"
    ].value_counts(
        normalize=True
    )
)

,household_id,sensitive_group,household_size,dwelling_type,electric_heating,energy_efficiency
0,0,B,5,house,0,high
1,1,A,1,house,1,medium
2,2,B,2,apartment,1,medium
3,3,B,3,apartment,1,low
4,4,A,4,house,0,medium

Shape households : (1000, 6)

sensitive_group
A    0.545
B    0.455
Name: proportion, dtype: float64

In [131]:
efficiency_by_group = pd.crosstab(
    households[
        "sensitive_group"
    ],
    households[
        "energy_efficiency"
    ],
    normalize="index",
)


display(
    efficiency_by_group
)

energy_efficiency      high       low    medium
sensitive_group
A                  0.266055  0.245872  0.488073
B                  0.138462  0.369231  0.492308

In [132]:
# ==========================================
# TEMPORAL GRID
# ==========================================

timestamps = pd.date_range(
    start="2025-01-14 00:00:00",
    periods=N_STEPS,
    freq=FREQUENCY,
    tz="UTC",
)


time_df = pd.DataFrame({
    "timestamp_utc":
        timestamps
})


display(
    time_df.head()
)

print(
    "Nombre de timestamps :",
    len(time_df)
)

              timestamp_utc
0 2025-01-14 00:00:00+00:00
1 2025-01-14 00:30:00+00:00
2 2025-01-14 01:00:00+00:00
3 2025-01-14 01:30:00+00:00
4 2025-01-14 02:00:00+00:00

Nombre de timestamps : 48

In [133]:
# ==========================================
# HOUSEHOLD X TIME
# ==========================================

microdata = households.merge(
    time_df,
    how="cross",
)


print(
    "Shape microdata :",
    microdata.shape
)

Shape microdata : (48000, 7)

In [134]:
hour = (
    microdata[
        "timestamp_utc"
    ]
    .dt.hour
    .to_numpy()
    +
    microdata[
        "timestamp_utc"
    ]
    .dt.minute
    .to_numpy()
    / 60
)


microdata[
    "hour"
] = hour

In [135]:
# ==========================================
# SYNTHETIC TEMPERATURE
# ==========================================

microdata[
    "temperature_c"
] = (
    2
    + 3
    * np.sin(
        2
        * np.pi
        * (
            microdata[
                "hour"
            ]
            - 14
        )
        / 24
    )
)

In [136]:
# ==========================================
# DAILY CONSUMPTION PROFILE
# ==========================================

morning_peak = np.exp(
    -0.5
    * (
        (
            microdata[
                "hour"
            ]
            - 8
        )
        / 1.5
    ) ** 2
)


evening_peak = np.exp(
    -0.5
    * (
        (
            microdata[
                "hour"
            ]
            - 19
        )
        / 2.0
    ) ** 2
)


microdata[
    "daily_profile"
] = (
    0.70
    + 0.60 * morning_peak
    + 0.90 * evening_peak
)

In [137]:
# ==========================================
# BASE CONSUMPTION
# ==========================================

base_consumption = (
    0.35
    + 0.18
    * microdata[
        "household_size"
    ]
)

In [138]:
# ==========================================
# HEATING EFFECT
# ==========================================

heating_effect = (
    microdata[
        "electric_heating"
    ]
    * np.maximum(
        0,
        15
        - microdata[
            "temperature_c"
        ]
    )
    * 0.025
)

In [139]:
# ==========================================
# DWELLING EFFECT
# ==========================================

dwelling_effect = np.where(
    microdata[
        "dwelling_type"
    ]
    == "house",
    0.30,
    0.0,
)

In [140]:
# ==========================================
# ENERGY EFFICIENCY EFFECT
# ==========================================

efficiency_effect = (
    microdata[
        "energy_efficiency"
    ]
    .map({
        "high":
            -0.10,

        "medium":
            0.00,

        "low":
            0.18,
    })
    .to_numpy()
)

In [141]:
# ==========================================
# RANDOM NOISE
# ==========================================

noise = rng.normal(
    loc=0.0,
    scale=0.12,
    size=len(
        microdata
    ),
)

In [142]:
# ==========================================
# SYNTHETIC ENERGY CONSUMPTION
# ==========================================

microdata[
    "consumption_kwh"
] = (
    base_consumption
    * microdata[
        "daily_profile"
    ]
    + heating_effect
    + dwelling_effect
    + efficiency_effect
    + noise
)


microdata[
    "consumption_kwh"
] = (
    microdata[
        "consumption_kwh"
    ]
    .clip(
        lower=0.05
    )
)

In [143]:
display(
    microdata.head()
)


display(
    microdata[
        "consumption_kwh"
    ].describe()
)

,household_id,sensitive_group,household_size,dwelling_type,electric_heating,energy_efficiency,timestamp_utc,hour,temperature_c,daily_profile,consumption_kwh
0,0,B,5,house,0,high,2025-01-14 00:00:00+00:00,0.0,3.500000,0.700000,0.881263
1,0,B,5,house,0,high,2025-01-14 00:30:00+00:00,0.5,3.148050,0.700002,0.986905
2,0,B,5,house,0,high,2025-01-14 01:00:00+00:00,1.0,2.776457,0.700011,0.833248
3,0,B,5,house,0,high,2025-01-14 01:30:00+00:00,1.5,2.391579,0.700050,0.952904
4,0,B,5,house,0,high,2025-01-14 02:00:00+00:00,2.0,2.000000,0.700201,1.219302

count    48000.000000
mean         1.173272
std          0.448650
min          0.050000
25%          0.851781
50%          1.133841
75%          1.454495
max          2.956942
Name: consumption_kwh, dtype: float64

In [144]:
observations_per_household = (
    microdata
    .groupby(
        "household_id"
    )
    .size()
)


display(
    observations_per_household
    .describe()
)

count    1000.0
mean       48.0
std         0.0
min        48.0
25%        48.0
50%        48.0
75%        48.0
max        48.0
dtype: float64

In [145]:
assert (
    observations_per_household.min()
    == N_STEPS
)

assert (
    observations_per_household.max()
    == N_STEPS
)


print(
    "48 observations par foyer : OK"
)

48 observations par foyer : OK

In [146]:
# ==========================================
# HOUSEHOLD-LEVEL FEATURES
# ==========================================

household_energy = (
    microdata
    .groupby(
        "household_id"
    )
    .agg(

        total_consumption_kwh=(
            "consumption_kwh",
            "sum"
        ),

        mean_consumption_kwh=(
            "consumption_kwh",
            "mean"
        ),

        peak_consumption_kwh=(
            "consumption_kwh",
            "max"
        ),

        mean_temperature_c=(
            "temperature_c",
            "mean"
        ),
    )
    .reset_index()
)

In [147]:
household_dataset = (
    households
    .merge(
        household_energy,
        on="household_id",
        how="left",
    )
)

In [148]:
# ==========================================
# CLASSIFICATION TARGET
# ==========================================

high_consumption_threshold = (
    household_dataset[
        "total_consumption_kwh"
    ]
    .quantile(
        0.75
    )
)


household_dataset[
    "high_consumption"
] = (
    household_dataset[
        "total_consumption_kwh"
    ]
    >= high_consumption_threshold
).astype(int)

In [149]:
print(
    "Seuil :",
    high_consumption_threshold
)


display(
    household_dataset[
        "high_consumption"
    ].value_counts(
        normalize=True
    )
)

Seuil : 67.5586364916943

high_consumption
0    0.75
1    0.25
Name: proportion, dtype: float64

In [150]:
# ==========================================
# TARGET BY SYNTHETIC GROUP
# ==========================================

target_by_group = (
    household_dataset
    .groupby(
        "sensitive_group"
    )
    .agg(

        n_households=(
            "household_id",
            "size"
        ),

        high_consumption_rate=(
            "high_consumption",
            "mean"
        ),

        mean_total_consumption=(
            "total_consumption_kwh",
            "mean"
        ),
    )
)


display(
    target_by_group
)

                 n_households  high_consumption_rate  mean_total_consumption
sensitive_group
A                         545               0.238532               55.114136
B                         455               0.263736               57.757926

In [151]:
# ==========================================
# DATA VALIDATION
# ==========================================

assert (
    len(
        households
    )
    == N_HOUSEHOLDS
)


assert (
    len(
        microdata
    )
    == (
        N_HOUSEHOLDS
        * N_STEPS
    )
)


assert (
    household_dataset[
        "household_id"
    ].nunique()
    == N_HOUSEHOLDS
)


assert (
    microdata[
        "consumption_kwh"
    ].isna().sum()
    == 0
)


assert (
    microdata[
        "consumption_kwh"
    ].min()
    > 0
)


assert (
    set(
        household_dataset[
            "high_consumption"
        ].unique()
    )
    <= {
        0,
        1,
    }
)


print(
    "Validation du sandbox : OK"
)

Validation du sandbox : OK

In [152]:
# ==========================================
# SAVE SYNTHETIC SANDBOX
# ==========================================

block11_sandbox = {

    "households":
        households,

    "microdata":
        microdata,

    "household_dataset":
        household_dataset,

    "high_consumption_threshold":
        high_consumption_threshold,

    "privacy_unit":
        "household_id",

    "n_households":
        N_HOUSEHOLDS,

    "observations_per_household":
        N_STEPS,

    "frequency":
        FREQUENCY,

    "synthetic":
        True,

    "privacy_enabled":
        PRIVACY_ENABLED,

    "uses_2026":
        False,

    "random_state":
        RANDOM_STATE,
}


joblib.dump(
    block11_sandbox,
    SYNTHETIC_PATH,
)


print(
    "Sauvegardé :",
    SYNTHETIC_PATH
)

print(
    "Existe :",
    SYNTHETIC_PATH.exists()
)

Sauvegardé : C:\Users\thiba\OneDrive\Bureau\Projet energie\data_processed\block11_synthetic_households.joblib
Existe : True

In [153]:
# ==========================================
# RELOAD SYNTHETIC SANDBOX
# ==========================================

sandbox = joblib.load(
    SYNTHETIC_PATH
)


households = sandbox[
    "households"
]

microdata = sandbox[
    "microdata"
]

household_dataset = sandbox[
    "household_dataset"
]


print(
    "Foyers :",
    len(
        household_dataset
    )
)

print(
    "Micro-observations :",
    len(
        microdata
    )
)

print(
    "Privacy :",
    sandbox[
        "privacy_enabled"
    ]
)

print(
    "2026 utilisé :",
    sandbox[
        "uses_2026"
    ]
)

Foyers : 1000
Micro-observations : 48000
Privacy : False
2026 utilisé : False

In [154]:
# ==========================================
# STEP 2 SUMMARY
# ==========================================

step2_summary = pd.DataFrame({

    "Élément": [
        "Foyers",
        "Observations temporelles",
        "Observations / foyer",
        "Groupes synthétiques",
        "Cible",
        "Privacy",
        "2026",
    ],

    "Valeur": [
        len(
            household_dataset
        ),

        len(
            microdata
        ),

        N_STEPS,

        "A / B",

        "High consumption",

        (
            "ON"
            if PRIVACY_ENABLED
            else "OFF"
        ),

        "Untouched",
    ],
})


display(
    step2_summary
)

                    Élément            Valeur
0                    Foyers              1000
1  Observations temporelles             48000
2      Observations / foyer                48
3      Groupes synthétiques             A / B
4                     Cible  High consumption
5                   Privacy               OFF
6                      2026         Untouched

### Partie C — Analyse et améliorations guidées par la théorie

Le sandbox contient deux niveaux d'observation.

Au niveau temporel, chaque foyer $i$ possède :

$$
x_i =
(x_{i1},\ldots,x_{i48}).
$$

Avec 1 000 foyers, le dataset contient :

$$
1000 \times 48
=
48\,000
$$

observations temporelles.

Une deuxième représentation agrège ces observations au niveau foyer.

Cette représentation sera utilisée pour l'apprentissage statistique et
l'étude de l'équité.

La cible binaire est définie par :

$$
Y_i =
\mathbf{1}
\left(
C_i
\geq
Q_{0.75}(C)
\right),
$$

où $C_i$ représente la consommation totale du foyer.

Ainsi, environ 25 % des foyers appartiennent à la classe positive.

Le groupe sensible utilisé dans le sandbox est entièrement synthétique.

Un léger déséquilibre structurel a volontairement été introduit dans
l'efficacité énergétique afin de créer un environnement dans lequel
les distributions des deux groupes ne sont pas nécessairement
identiques.

Cette construction ne doit pas être interprétée comme une observation
sur un véritable groupe de population.

Elle constitue uniquement un environnement contrôlé permettant
d'étudier ensuite les métriques d'équité.

La Privacy reste désactivée :

$$
Privacy = OFF.
$$

Aucun bruit ni mécanisme de confidentialité n'a donc été appliqué aux
données.

Conclusion :

Un sandbox synthétique de 1 000 foyers a été construit pour permettre
les futures expériences de confidentialité et d'équité.

Chaque foyer possède 48 observations temporelles, donnant un total de
48 000 micro-observations.

Une représentation agrégée au niveau foyer ainsi qu'une cible de forte
consommation ont également été créées.

Les groupes utilisés dans ce sandbox sont entièrement synthétiques et
servent uniquement aux expériences méthodologiques du Bloc 11.

La Privacy reste désactivée par défaut et aucune donnée de 2026 n'est
utilisée.

## Étape 3 — Anonymisation et \(k\)-anonymité

### Partie A — Mise en pratique

Cette étape étudie différentes méthodes classiques de protection des
microdonnées :

- suppression des identifiants directs ;
- pseudonymisation ;
- identification des quasi-identifiants ;
- généralisation ;
- suppression ;
- k-anonymité.

Ces transformations sont réalisées uniquement sur le sandbox
synthétique.

Le pipeline énergétique principal reste inchangé :

`PRIVACY_ENABLED = False`.

In [155]:
# ==========================================
# LOAD BLOCK 11 SANDBOX
# ==========================================

if "household_dataset" not in globals():

    sandbox = joblib.load(
        SYNTHETIC_PATH
    )

    households = sandbox[
        "households"
    ]

    microdata = sandbox[
        "microdata"
    ]

    household_dataset = sandbox[
        "household_dataset"
    ]


print(
    "Foyers disponibles :",
    len(household_dataset)
)

Foyers disponibles : 1000

In [156]:
# ==========================================
# VARIABLE TYPES
# ==========================================

DIRECT_IDENTIFIERS = [
    "household_id",
]


QUASI_IDENTIFIERS = [
    "household_size",
    "dwelling_type",
    "electric_heating",
    "energy_efficiency",
]


SENSITIVE_ATTRIBUTES = [
    "sensitive_group",
]


TARGET_COLUMNS = [
    "high_consumption",
]


print(
    "Identifiants directs :",
    DIRECT_IDENTIFIERS
)

print(
    "Quasi-identifiants :",
    QUASI_IDENTIFIERS
)

print(
    "Attribut sensible :",
    SENSITIVE_ATTRIBUTES
)

Identifiants directs : ['household_id']
Quasi-identifiants : ['household_size', 'dwelling_type', 'electric_heating', 'energy_efficiency']
Attribut sensible : ['sensitive_group']

In [157]:
# ==========================================
# REMOVE DIRECT IDENTIFIER
# ==========================================

naive_anonymized = (
    household_dataset
    .drop(
        columns=DIRECT_IDENTIFIERS
    )
    .copy()
)


display(
    naive_anonymized.head()
)

,sensitive_group,household_size,dwelling_type,electric_heating,energy_efficiency,total_consumption_kwh,mean_consumption_kwh,peak_consumption_kwh,mean_temperature_c,high_consumption
0,B,5,house,0,high,67.015862,1.396164,2.187028,2.0,0
1,A,1,house,1,medium,55.375379,1.153654,1.521793,2.0,0
2,B,2,apartment,1,medium,48.492363,1.010258,1.526063,2.0,0
3,B,3,apartment,1,low,64.855841,1.351163,1.874057,2.0,0
4,A,4,house,0,medium,64.252716,1.338598,2.025344,2.0,0

In [158]:
# ==========================================
# EQUIVALENCE CLASSES
# ==========================================

equivalence_sizes = (
    household_dataset
    .groupby(
        QUASI_IDENTIFIERS,
        dropna=False,
    )
    .size()
    .rename(
        "equivalence_size"
    )
    .reset_index()
)


display(
    equivalence_sizes
    .sort_values(
        "equivalence_size"
    )
    .head(10)
)

,household_size,dwelling_type,electric_heating,energy_efficiency,equivalence_size
21,2,house,1,high,4
33,3,house,1,high,6
57,5,house,1,high,7
3,1,apartment,1,high,7
39,4,apartment,1,high,7
9,1,house,1,high,7
27,3,apartment,1,high,7
18,2,house,0,high,8
45,4,house,1,high,8
34,3,house,1,low,9

In [159]:
# ==========================================
# K-ANONYMITY LEVEL
# ==========================================

k_initial = int(
    equivalence_sizes[
        "equivalence_size"
    ].min()
)


print(
    "k initial :",
    k_initial
)

k initial : 4

In [160]:
# ==========================================
# REIDENTIFICATION RISK
# ==========================================

dataset_with_k = (
    household_dataset
    .merge(
        equivalence_sizes,
        on=QUASI_IDENTIFIERS,
        how="left",
    )
)


risk_summary = pd.DataFrame({

    "Threshold": [
        "< 2",
        "< 3",
        "< 5",
        "< 10",
    ],

    "Households": [
        int(
            (
                dataset_with_k[
                    "equivalence_size"
                ] < 2
            ).sum()
        ),

        int(
            (
                dataset_with_k[
                    "equivalence_size"
                ] < 3
            ).sum()
        ),

        int(
            (
                dataset_with_k[
                    "equivalence_size"
                ] < 5
            ).sum()
        ),

        int(
            (
                dataset_with_k[
                    "equivalence_size"
                ] < 10
            ).sum()
        ),
    ],
})


risk_summary[
    "Share_percent"
] = (
    100
    * risk_summary[
        "Households"
    ]
    / len(
        household_dataset
    )
)


display(
    risk_summary
)

  Threshold  Households  Share_percent
0       < 2           0            0.0
1       < 3           0            0.0
2       < 5           4            0.4
3      < 10          97            9.7

In [161]:
# ==========================================
# GENERALIZE HOUSEHOLD SIZE
# ==========================================

anonymized_df = (
    household_dataset
    .copy()
)


anonymized_df[
    "household_size_group"
] = pd.cut(
    anonymized_df[
        "household_size"
    ],
    bins=[
        0,
        2,
        4,
        np.inf,
    ],
    labels=[
        "1-2",
        "3-4",
        "5+",
    ],
)

In [162]:
anonymized_df = (
    anonymized_df
    .drop(
        columns=[
            "household_size"
        ]
    )
)

In [163]:
# ==========================================
# GENERALIZE ENERGY EFFICIENCY
# ==========================================

anonymized_df[
    "energy_efficiency_group"
] = (
    anonymized_df[
        "energy_efficiency"
    ]
    .replace({
        "high":
            "not_low",

        "medium":
            "not_low",

        "low":
            "low",
    })
)


anonymized_df = (
    anonymized_df
    .drop(
        columns=[
            "energy_efficiency"
        ]
    )
)

In [164]:
# ==========================================
# GENERALIZED QUASI IDENTIFIERS
# ==========================================

GENERALIZED_QI = [

    "household_size_group",

    "dwelling_type",

    "electric_heating",

    "energy_efficiency_group",
]

In [165]:
generalized_equivalence = (
    anonymized_df
    .groupby(
        GENERALIZED_QI,
        observed=True,
        dropna=False,
    )
    .size()
    .rename(
        "equivalence_size"
    )
    .reset_index()
)


k_generalized = int(
    generalized_equivalence[
        "equivalence_size"
    ].min()
)


print(
    "k avant généralisation :",
    k_initial
)

print(
    "k après généralisation :",
    k_generalized
)

k avant généralisation : 4
k après généralisation : 9

In [166]:
# ==========================================
# TARGET K
# ==========================================

TARGET_K = 5


anonymized_with_k = (
    anonymized_df
    .merge(
        generalized_equivalence,
        on=GENERALIZED_QI,
        how="left",
    )
)

In [167]:
k5_dataset = (
    anonymized_with_k[
        anonymized_with_k[
            "equivalence_size"
        ]
        >= TARGET_K
    ]
    .copy()
)

In [168]:
# ==========================================
# SUPPRESSION RATE
# ==========================================

n_original = len(
    anonymized_with_k
)

n_k5 = len(
    k5_dataset
)


n_suppressed = (
    n_original
    - n_k5
)


suppression_rate = (
    100
    * n_suppressed
    / n_original
)


print(
    "Observations initiales :",
    n_original
)

print(
    "Observations conservées :",
    n_k5
)

print(
    "Observations supprimées :",
    n_suppressed
)

print(
    "Taux de suppression :",
    f"{suppression_rate:.2f} %"
)

Observations initiales : 1000
Observations conservées : 1000
Observations supprimées : 0
Taux de suppression : 0.00 %

In [169]:
# ==========================================
# VERIFY K-ANONYMITY
# ==========================================

final_equivalence = (
    k5_dataset
    .groupby(
        GENERALIZED_QI,
        observed=True,
        dropna=False,
    )
    .size()
)


final_k = int(
    final_equivalence.min()
)


print(
    "k final :",
    final_k
)


assert (
    final_k
    >= TARGET_K
)


print(
    "k-anonymité vérifiée : OK"
)

k final : 9
k-anonymité vérifiée : OK

In [170]:
import hashlib

# ==========================================
# PSEUDONYMIZATION
# ==========================================

def pseudonymize_household(
    household_id
):

    raw_value = (
        f"block11-{household_id}"
        .encode(
            "utf-8"
        )
    )

    return hashlib.sha256(
        raw_value
    ).hexdigest()[:16]

In [171]:
pseudonymized_df = (
    household_dataset
    .copy()
)


pseudonymized_df[
    "household_pseudo_id"
] = (
    pseudonymized_df[
        "household_id"
    ]
    .apply(
        pseudonymize_household
    )
)


pseudonymized_df = (
    pseudonymized_df
    .drop(
        columns=[
            "household_id"
        ]
    )
)


display(
    pseudonymized_df[
        [
            "household_pseudo_id",
            "household_size",
            "dwelling_type",
        ]
    ]
    .head()
)

  household_pseudo_id  household_size dwelling_type
0    c88baf2861c4ac9d               5         house
1    fd5ebf1fe3c11e9a               1         house
2    b241c6061fbebe1a               2     apartment
3    da4afd9535ed138a               3     apartment
4    4119180490cee5ba               4         house

In [172]:
# ==========================================
# METHOD COMPARISON
# ==========================================

anonymization_summary = pd.DataFrame({

    "Méthode": [
        "Données originales",
        "Suppression ID",
        "Pseudonymisation",
        "Généralisation",
        "k-anonymité k=5",
    ],

    "Identifiant direct": [
        "Oui",
        "Non",
        "Pseudonyme",
        "Non",
        "Non",
    ],

    "Quasi-identifiants détaillés": [
        "Oui",
        "Oui",
        "Oui",
        "Partiellement",
        "Partiellement",
    ],

    "Protection supplémentaire": [
        "Aucune",
        "Faible",
        "Faible",
        "Modérée",
        "k >= 5",
    ],
})


display(
    anonymization_summary
)

,Méthode,Identifiant direct,Quasi-identifiants détaillés,Protection supplémentaire
0,Données originales,Oui,Oui,Aucune
1,Suppression ID,Non,Oui,Faible
2,Pseudonymisation,Pseudonyme,Oui,Faible
3,Généralisation,Non,Partiellement,Modérée
4,k-anonymité k=5,Non,Partiellement,k >= 5

In [173]:
# ==========================================
# PRIVACY ON / OFF DECISION
# ==========================================

if PRIVACY_ENABLED:

    selected_dataset = (
        k5_dataset.copy()
    )

    selected_privacy_mode = (
        "k-anonymized"
    )

else:

    selected_dataset = (
        household_dataset.copy()
    )

    selected_privacy_mode = (
        "original-public-pipeline"
    )


print(
    "Dataset retenu :",
    selected_privacy_mode
)

print(
    "Nombre d'observations :",
    len(selected_dataset)
)

Dataset retenu : original-public-pipeline
Nombre d'observations : 1000

In [174]:
# ==========================================
# SAVE STEP 3
# ==========================================

STEP3_PATH = (
    DATA_DIR
    / "block11_anonymization.joblib"
)


step3_state = {

    "k_initial":
        k_initial,

    "k_generalized":
        k_generalized,

    "target_k":
        TARGET_K,

    "final_k":
        final_k,

    "suppression_rate":
        suppression_rate,

    "anonymized_dataset":
        k5_dataset,

    "pseudonymized_dataset":
        pseudonymized_df,

    "selected_privacy_mode":
        selected_privacy_mode,

    "privacy_enabled":
        PRIVACY_ENABLED,

    "uses_2026":
        False,
}


joblib.dump(
    step3_state,
    STEP3_PATH
)


print(
    "Sauvegardé :",
    STEP3_PATH
)

Sauvegardé : C:\Users\thiba\OneDrive\Bureau\Projet energie\data_processed\block11_anonymization.joblib

In [175]:
# ==========================================
# STEP 3 SUMMARY
# ==========================================

step3_summary = pd.DataFrame({

    "Indicateur": [
        "k initial",
        "k après généralisation",
        "k cible",
        "k final",
        "Taux suppression (%)",
        "Privacy production",
        "2026",
    ],

    "Valeur": [
        k_initial,
        k_generalized,
        TARGET_K,
        final_k,
        suppression_rate,
        (
            "ON"
            if PRIVACY_ENABLED
            else "OFF"
        ),
        "Untouched",
    ],
})


display(
    step3_summary
)

               Indicateur     Valeur
0               k initial          4
1  k après généralisation          9
2                 k cible          5
3                 k final          9
4    Taux suppression (%)        0.0
5      Privacy production        OFF
6                    2026  Untouched

### Partie C — Analyse et améliorations guidées par la théorie

La suppression d'un identifiant direct ne garantit pas à elle seule
l'anonymat.

Un individu peut parfois être distingué grâce à une combinaison de
quasi-identifiants.

Une classe d'équivalence regroupe les observations possédant les mêmes
valeurs de quasi-identifiants.

Le niveau de k-anonymité est défini par :

$$
k =
\min_g |G_g|,
$$

où $G_g$ représente une classe d'équivalence.

Un dataset est k-anonyme lorsque chaque combinaison de
quasi-identifiants correspond à au moins $k$ individus.

La généralisation réduit la précision de certaines variables afin
d'augmenter la taille des classes d'équivalence.

La suppression permet ensuite de retirer les observations appartenant
aux classes encore trop petites.

Cette méthode introduit cependant un compromis entre protection et
utilité :

$$
\text{Protection}\uparrow
\quad\Rightarrow\quad
\text{Précision des données}\downarrow.
$$

La pseudonymisation ne doit pas être confondue avec l'anonymisation.

Elle remplace un identifiant par un autre identifiant stable, mais les
observations correspondant au même individu peuvent encore être
reliées.

Enfin, la k-anonymité ne fournit pas une garantie probabiliste aussi
forte que la Differential Privacy.

Elle sera donc utilisée ici comme méthode introductive avant l'étude
des mécanismes de confidentialité différentielle.

Conclusion :

L'Étape 3 montre que supprimer un identifiant direct n'est pas
suffisant pour anonymiser un jeu de microdonnées.

Les quasi-identifiants peuvent créer des profils rares et permettre de
distinguer certains foyers.

La généralisation et la suppression permettent d'augmenter le niveau
de k-anonymité, au prix d'une perte d'information.

Ces transformations restent uniquement expérimentales dans ce projet.

Comme `PRIVACY_ENABLED = False`, le pipeline énergétique principal
continue d'utiliser les données publiques sans perturbation.

Aucune donnée de 2026 n'a été utilisée.

## Étape 4 — Differential Privacy

### Partie A — Mise en pratique

## Étape 4 — Differential Privacy

La confidentialité différentielle cherche à limiter l'influence d'une
unité individuelle sur le résultat publié par un algorithme.

Un mécanisme aléatoire $\mathcal{M}$ satisfait une garantie
$\varepsilon$-Differential Privacy si, pour deux datasets voisins
$D$ et $D'$ :

$$
P(\mathcal{M}(D)\in S)
\leq
e^\varepsilon
P(\mathcal{M}(D')\in S)
$$

pour tout ensemble de sorties possibles $S$.

Le paramètre :

$$
\varepsilon
$$

contrôle le compromis entre confidentialité et utilité.

Un petit $\varepsilon$ implique généralement davantage de bruit et une
protection plus forte.

Un grand $\varepsilon$ implique généralement moins de bruit et une
protection plus faible.

Dans ce projet, ces mécanismes sont étudiés uniquement dans le sandbox
synthétique.

Le pipeline énergétique principal conserve :

`PRIVACY_ENABLED = False`.

In [176]:
# ==========================================
# PRIVATE QUERY — HIGH CONSUMPTION COUNT
# ==========================================

true_high_count = int(
    household_dataset[
        "high_consumption"
    ].sum()
)


print(
    "Nombre réel de foyers "
    "high consumption :",
    true_high_count
)

Nombre réel de foyers high consumption : 250

In [177]:
# ==========================================
# GLOBAL SENSITIVITY
# ==========================================

COUNT_SENSITIVITY = 1.0


print(
    "Sensibilité du comptage :",
    COUNT_SENSITIVITY
)

Sensibilité du comptage : 1.0

In [178]:
# ==========================================
# LAPLACE MECHANISM
# ==========================================

def laplace_mechanism(
    value,
    sensitivity,
    epsilon,
    random_generator,
):

    if epsilon <= 0:

        raise ValueError(
            "epsilon doit être > 0."
        )

    scale = (
        sensitivity
        / epsilon
    )

    noise = (
        random_generator
        .laplace(
            loc=0.0,
            scale=scale,
        )
    )

    return (
        value + noise
    )

In [179]:
# ==========================================
# EPSILON GRID
# ==========================================

EPSILON_VALUES = [
    0.1,
    0.5,
    1.0,
    2.0,
    5.0,
    10.0,
]

In [180]:
# ==========================================
# SINGLE DP RELEASE
# ==========================================

single_release_results = []


if RUN_PRIVACY_LAB:

    for epsilon in EPSILON_VALUES:

        private_count = (
            laplace_mechanism(
                value=true_high_count,
                sensitivity=COUNT_SENSITIVITY,
                epsilon=epsilon,
                random_generator=rng,
            )
        )


        single_release_results.append({

            "epsilon":
                epsilon,

            "true_count":
                true_high_count,

            "private_count":
                private_count,

            "absolute_error":
                abs(
                    private_count
                    - true_high_count
                ),

            "laplace_scale":
                (
                    COUNT_SENSITIVITY
                    / epsilon
                ),
        })


single_release_df = pd.DataFrame(
    single_release_results
)


display(
    single_release_df
)

   epsilon  true_count  private_count  absolute_error  laplace_scale
0      0.1         250     250.483759        0.483759           10.0
1      0.5         250     253.167780        3.167780            2.0
2      1.0         250     250.057010        0.057010            1.0
3      2.0         250     249.679985        0.320015            0.5
4      5.0         250     250.103479        0.103479            0.2
5     10.0         250     249.936455        0.063545            0.1

In [181]:
N_DP_SIMULATIONS = 500

In [182]:
# ==========================================
# MONTE CARLO DP EXPERIMENT
# ==========================================

N_DP_SIMULATIONS = 500


dp_results = []


if RUN_PRIVACY_LAB:

    for epsilon in EPSILON_VALUES:

        scale = (
            COUNT_SENSITIVITY
            / epsilon
        )


        noises = rng.laplace(
            loc=0.0,
            scale=scale,
            size=N_DP_SIMULATIONS,
        )


        private_values = (
            true_high_count
            + noises
        )


        errors = (
            private_values
            - true_high_count
        )


        dp_results.append({

            "epsilon":
                epsilon,

            "scale":
                scale,

            "mean_private_count":
                np.mean(
                    private_values
                ),

            "bias":
                np.mean(
                    errors
                ),

            "mae":
                np.mean(
                    np.abs(
                        errors
                    )
                ),

            "rmse":
                np.sqrt(
                    np.mean(
                        errors ** 2
                    )
                ),

            "error_std":
                np.std(
                    errors
                ),
        })

In [183]:
dp_results_df = pd.DataFrame(
    dp_results
)


display(
    dp_results_df
)

,epsilon,scale,mean_private_count,bias,mae,rmse,error_std
0,0.1,10.0,248.755902,-1.244098,10.578911,14.711279,14.658579
1,0.5,2.0,250.053232,0.053232,1.912325,2.681148,2.680620
2,1.0,1.0,249.969509,-0.030491,1.068424,1.520733,1.520427
3,2.0,0.5,249.994912,-0.005088,0.485590,0.682008,0.681989
4,5.0,0.2,249.976353,-0.023647,0.193923,0.271307,0.270275
5,10.0,0.1,250.011170,0.011170,0.106589,0.148069,0.147647

In [184]:
dp_results_df[
    "theoretical_rmse"
] = (
    np.sqrt(2)
    * dp_results_df[
        "scale"
    ]
)


dp_results_df[
    "rmse_gap"
] = (
    dp_results_df[
        "rmse"
    ]
    - dp_results_df[
        "theoretical_rmse"
    ]
)


display(
    dp_results_df
)

,epsilon,scale,mean_private_count,bias,mae,rmse,error_std,theoretical_rmse,rmse_gap
0,0.1,10.0,248.755902,-1.244098,10.578911,14.711279,14.658579,14.142136,0.569143
1,0.5,2.0,250.053232,0.053232,1.912325,2.681148,2.680620,2.828427,-0.147279
2,1.0,1.0,249.969509,-0.030491,1.068424,1.520733,1.520427,1.414214,0.106519
3,2.0,0.5,249.994912,-0.005088,0.485590,0.682008,0.681989,0.707107,-0.025098
4,5.0,0.2,249.976353,-0.023647,0.193923,0.271307,0.270275,0.282843,-0.011536
5,10.0,0.1,250.011170,0.011170,0.106589,0.148069,0.147647,0.141421,0.006647

In [185]:
dp_results_df[
    "relative_mae_percent"
] = (
    100
    * dp_results_df[
        "mae"
    ]
    / true_high_count
)


display(
    dp_results_df[
        [
            "epsilon",
            "mae",
            "rmse",
            "theoretical_rmse",
            "relative_mae_percent",
        ]
    ]
)

   epsilon        mae       rmse  theoretical_rmse  relative_mae_percent
0      0.1  10.578911  14.711279         14.142136              4.231564
1      0.5   1.912325   2.681148          2.828427              0.764930
2      1.0   1.068424   1.520733          1.414214              0.427370
3      2.0   0.485590   0.682008          0.707107              0.194236
4      5.0   0.193923   0.271307          0.282843              0.077569
5     10.0   0.106589   0.148069          0.141421              0.042636

In [186]:
# ==========================================
# CONTRIBUTION CLIPPING
# ==========================================

CONSUMPTION_MIN = 0.0

CONSUMPTION_MAX = 100.0


clipped_total_consumption = (
    household_dataset[
        "total_consumption_kwh"
    ]
    .clip(
        lower=CONSUMPTION_MIN,
        upper=CONSUMPTION_MAX,
    )
)

In [187]:
true_total_consumption = (
    clipped_total_consumption.sum()
)


SUM_SENSITIVITY = (
    CONSUMPTION_MAX
    - CONSUMPTION_MIN
)


print(
    "Consommation totale :",
    true_total_consumption
)

print(
    "Sensibilité :",
    SUM_SENSITIVITY
)

Consommation totale : 56317.060459993285
Sensibilité : 100.0

In [188]:
# ==========================================
# PRIVATE TOTAL CONSUMPTION
# ==========================================

private_sum_results = []


if RUN_PRIVACY_LAB:

    for epsilon in EPSILON_VALUES:

        private_total = (
            laplace_mechanism(
                value=true_total_consumption,
                sensitivity=SUM_SENSITIVITY,
                epsilon=epsilon,
                random_generator=rng,
            )
        )


        private_sum_results.append({

            "epsilon":
                epsilon,

            "true_total_kwh":
                true_total_consumption,

            "private_total_kwh":
                private_total,

            "absolute_error_kwh":
                abs(
                    private_total
                    - true_total_consumption
                ),

            "scale":
                (
                    SUM_SENSITIVITY
                    / epsilon
                ),
        })


private_sum_df = pd.DataFrame(
    private_sum_results
)


display(
    private_sum_df
)

   epsilon  true_total_kwh  private_total_kwh  absolute_error_kwh   scale
0      0.1     56317.06046       55942.226116          374.834344  1000.0
1      0.5     56317.06046       56149.868236          167.192224   200.0
2      1.0     56317.06046       56306.481193           10.579267   100.0
3      2.0     56317.06046       56307.950157            9.110303    50.0
4      5.0     56317.06046       56386.596837           69.536377    20.0
5     10.0     56317.06046       56304.689954           12.370506    10.0

### Importance du clipping

La sensibilité d'une somme dépend de la contribution maximale qu'un
utilisateur peut apporter.

Sans borne sur la consommation individuelle, la sensibilité globale
de la somme peut devenir non bornée.

On impose donc :

$$
0 \leq C_i \leq 100.
$$

La sensibilité de la somme devient alors :

$$
\Delta f = 100.
$$

Le clipping joue donc un rôle fondamental dans la calibration du bruit
de confidentialité différentielle.

Une borne trop grande augmente inutilement le bruit.

Une borne trop petite tronque fortement les données.

Il existe donc également un compromis entre :

$$
\text{clipping}
\quad\text{et}\quad
\text{utilité}.
$$

In [189]:
# ==========================================
# SAVE STEP 4
# ==========================================

STEP4_PATH = (
    DATA_DIR
    / "block11_differential_privacy.joblib"
)


step4_state = {

    "privacy_enabled":
        PRIVACY_ENABLED,

    "privacy_lab_enabled":
        RUN_PRIVACY_LAB,

    "epsilon_values":
        EPSILON_VALUES,

    "true_high_count":
        true_high_count,

    "count_sensitivity":
        COUNT_SENSITIVITY,

    "count_results":
        dp_results_df,

    "consumption_min":
        CONSUMPTION_MIN,

    "consumption_max":
        CONSUMPTION_MAX,

    "sum_sensitivity":
        SUM_SENSITIVITY,

    "sum_results":
        private_sum_df,

    "uses_2026":
        False,
}


joblib.dump(
    step4_state,
    STEP4_PATH
)


print(
    "Sauvegardé :",
    STEP4_PATH
)

Sauvegardé : C:\Users\thiba\OneDrive\Bureau\Projet energie\data_processed\block11_differential_privacy.joblib

In [190]:
# ==========================================
# STEP 4 SUMMARY
# ==========================================

step4_summary = (
    dp_results_df[
        [
            "epsilon",
            "scale",
            "mae",
            "rmse",
            "theoretical_rmse",
            "relative_mae_percent",
        ]
    ]
    .copy()
)


display(
    step4_summary
)

,epsilon,scale,mae,rmse,theoretical_rmse,relative_mae_percent
0,0.1,10.0,10.578911,14.711279,14.142136,4.231564
1,0.5,2.0,1.912325,2.681148,2.828427,0.764930
2,1.0,1.0,1.068424,1.520733,1.414214,0.427370
3,2.0,0.5,0.485590,0.682008,0.707107,0.194236
4,5.0,0.2,0.193923,0.271307,0.282843,0.077569
5,10.0,0.1,0.106589,0.148069,0.141421,0.042636

Conclusion :

L'Étape 4 introduit la Differential Privacy et montre que la quantité
de bruit dépend à la fois du budget epsilon et de la sensibilité de la
requête.

Les comptages sont relativement faciles à protéger grâce à leur faible
sensibilité, tandis que les sommes de consommation nécessitent de
borner les contributions individuelles avant d'ajouter du bruit.

Le clipping constitue donc une étape essentielle de la calibration
d'un mécanisme privé.

Ces mécanismes sont uniquement étudiés dans le laboratoire synthétique
du Bloc 11 et ne sont pas appliqués au pipeline énergétique public.

L'année 2026 reste totalement inutilisée.

## Étape 5 — User-Level Differential Privacy, composition et compromis Privacy–Utility

### Partie A — Mise en pratique

Les observations du sandbox possèdent une structure hiérarchique :

- plusieurs lignes correspondent au même foyer ;
- un foyer possède 48 observations temporelles.

Une protection définie ligne par ligne n'est donc pas nécessairement
équivalente à une protection définie au niveau du foyer.

Cette étape étudie :

- la différence entre Row-Level DP et User-Level DP ;
- la composition des budgets de confidentialité ;
- l'effet de requêtes répétées ;
- le compromis entre clipping, bruit et utilité.

Ces expériences restent confinées au sandbox synthétique.

Le pipeline énergétique principal conserve :

`PRIVACY_ENABLED = False`.

In [191]:
# ==========================================
# ROW-LEVEL VS USER-LEVEL SENSITIVITY
# ==========================================

ROWS_PER_HOUSEHOLD = N_STEPS


ROW_LEVEL_SENSITIVITY = 1

USER_LEVEL_SENSITIVITY = (
    ROWS_PER_HOUSEHOLD
)


sensitivity_comparison = pd.DataFrame({

    "Privacy level": [
        "Row-level",
        "User-level",
    ],

    "Maximum contribution": [
        1,
        ROWS_PER_HOUSEHOLD,
    ],

    "Count sensitivity": [
        ROW_LEVEL_SENSITIVITY,
        USER_LEVEL_SENSITIVITY,
    ],
})


display(
    sensitivity_comparison
)

  Privacy level  Maximum contribution  Count sensitivity
0     Row-level                     1                  1
1    User-level                    48                 48

In [192]:
# ==========================================
# SENSITIVITY EFFECT ON NOISE
# ==========================================

EXAMPLE_EPSILON = 1.0


row_scale = (
    ROW_LEVEL_SENSITIVITY
    / EXAMPLE_EPSILON
)


user_scale = (
    USER_LEVEL_SENSITIVITY
    / EXAMPLE_EPSILON
)


print(
    "Laplace scale — Row-level :",
    row_scale
)

print(
    "Laplace scale — User-level :",
    user_scale
)

Laplace scale — Row-level : 1.0
Laplace scale — User-level : 48.0

### Agrégation préalable au niveau utilisateur

La User-Level Differential Privacy ne signifie pas automatiquement que
toutes les sensibilités sont multipliées par le nombre de lignes par
utilisateur.

Si les contributions temporelles sont d'abord agrégées au niveau du
foyer, chaque utilisateur peut de nouveau ne contribuer qu'une seule
valeur.

Pour le comptage :

$$
f(D)=\sum_i Y_i,
$$

avec :

$$
Y_i\in\{0,1\},
$$

la sensibilité utilisateur reste :

$$
\Delta f=1.
$$

L'agrégation par utilisateur constitue donc une technique importante
pour limiter la sensibilité.

In [193]:
# ==========================================
# PRIVACY BUDGET COMPOSITION
# ==========================================

TOTAL_EPSILON_BUDGET = 1.0


QUERY_COUNTS = [
    1,
    2,
    5,
    10,
    20,
]


composition_rows = []


for n_queries in QUERY_COUNTS:

    epsilon_per_query = (
        TOTAL_EPSILON_BUDGET
        / n_queries
    )

    scale_per_query = (
        COUNT_SENSITIVITY
        / epsilon_per_query
    )

    composition_rows.append({

        "n_queries":
            n_queries,

        "epsilon_total":
            TOTAL_EPSILON_BUDGET,

        "epsilon_per_query":
            epsilon_per_query,

        "laplace_scale":
            scale_per_query,
    })


composition_df = pd.DataFrame(
    composition_rows
)


display(
    composition_df
)

   n_queries  epsilon_total  epsilon_per_query  laplace_scale
0          1            1.0               1.00            1.0
1          2            1.0               0.50            2.0
2          5            1.0               0.20            5.0
3         10            1.0               0.10           10.0
4         20            1.0               0.05           20.0

In [194]:
# ==========================================
# COMPOSITION MONTE CARLO
# ==========================================

N_COMPOSITION_SIMULATIONS = 500


rng_step5 = np.random.default_rng(
    RANDOM_STATE + 5
)


composition_results = []


for n_queries in QUERY_COUNTS:

    epsilon_per_query = (
        TOTAL_EPSILON_BUDGET
        / n_queries
    )

    scale = (
        COUNT_SENSITIVITY
        / epsilon_per_query
    )


    simulation_errors = []


    for _ in range(
        N_COMPOSITION_SIMULATIONS
    ):

        noises = rng_step5.laplace(
            loc=0.0,
            scale=scale,
            size=n_queries,
        )

        mean_release = (
            true_high_count
            + np.mean(
                noises
            )
        )

        simulation_errors.append(
            mean_release
            - true_high_count
        )


    simulation_errors = np.array(
        simulation_errors
    )


    empirical_rmse = np.sqrt(
        np.mean(
            simulation_errors ** 2
        )
    )


    theoretical_rmse = (
        np.sqrt(2)
        * COUNT_SENSITIVITY
        * np.sqrt(
            n_queries
        )
        / TOTAL_EPSILON_BUDGET
    )


    composition_results.append({

        "n_queries":
            n_queries,

        "epsilon_per_query":
            epsilon_per_query,

        "empirical_rmse":
            empirical_rmse,

        "theoretical_rmse":
            theoretical_rmse,
    })

In [195]:
composition_results_df = pd.DataFrame(
    composition_results
)


display(
    composition_results_df
)

   n_queries  epsilon_per_query  empirical_rmse  theoretical_rmse
0          1               1.00        1.403295          1.414214
1          2               0.50        2.088794          2.000000
2          5               0.20        3.093634          3.162278
3         10               0.10        4.399046          4.472136
4         20               0.05        6.329944          6.324555

In [196]:
# ==========================================
# NAIVE PRIVACY BUDGET
# ==========================================

NAIVE_EPSILON_PER_QUERY = 1.0


naive_composition = pd.DataFrame({

    "n_queries":
        QUERY_COUNTS,

    "epsilon_per_query":
        [
            NAIVE_EPSILON_PER_QUERY
        ]
        * len(
            QUERY_COUNTS
        ),
})


naive_composition[
    "epsilon_total"
] = (
    naive_composition[
        "n_queries"
    ]
    * naive_composition[
        "epsilon_per_query"
    ]
)


display(
    naive_composition
)

   n_queries  epsilon_per_query  epsilon_total
0          1                1.0            1.0
1          2                1.0            2.0
2          5                1.0            5.0
3         10                1.0           10.0
4         20                1.0           20.0

In [197]:
# ==========================================
# CLIPPING GRID
# ==========================================

CLIPPING_BOUNDS = [
    50.0,
    60.0,
    70.0,
    80.0,
    100.0,
]


CLIPPING_EPSILON = 1.0


true_unclipped_sum = (
    household_dataset[
        "total_consumption_kwh"
    ].sum()
)

In [198]:
# ==========================================
# CLIPPING / PRIVACY TRADE-OFF
# ==========================================

clipping_results = []


for upper_bound in CLIPPING_BOUNDS:

    clipped_values = (
        household_dataset[
            "total_consumption_kwh"
        ]
        .clip(
            lower=0.0,
            upper=upper_bound,
        )
    )


    clipped_sum = (
        clipped_values.sum()
    )


    clipping_bias = (
        clipped_sum
        - true_unclipped_sum
    )


    sensitivity = (
        upper_bound
    )


    dp_rmse = (
        np.sqrt(2)
        * sensitivity
        / CLIPPING_EPSILON
    )


    total_expected_rmse = np.sqrt(
        clipping_bias ** 2
        + dp_rmse ** 2
    )


    clipped_share = (
        100
        * (
            household_dataset[
                "total_consumption_kwh"
            ]
            > upper_bound
        ).mean()
    )


    clipping_results.append({

        "upper_bound_kwh":
            upper_bound,

        "clipped_share_percent":
            clipped_share,

        "clipping_bias_kwh":
            clipping_bias,

        "dp_theoretical_rmse":
            dp_rmse,

        "combined_expected_rmse":
            total_expected_rmse,
    })

In [199]:
clipping_results_df = pd.DataFrame(
    clipping_results
)


display(
    clipping_results_df
)

,upper_bound_kwh,clipped_share_percent,clipping_bias_kwh,dp_theoretical_rmse,combined_expected_rmse
0,50.0,63.7,-10393.014167,70.710678,10393.254710
1,60.0,38.9,-5102.626484,84.852814,5103.331954
2,70.0,21.9,-1995.982203,98.994949,1998.435627
3,80.0,9.6,-559.649640,113.137085,570.970857
4,100.0,0.0,0.000000,141.421356,141.421356

In [200]:
# ==========================================
# BEST CLIPPING BOUND
# ==========================================

best_clipping_row = (
    clipping_results_df
    .sort_values(
        "combined_expected_rmse"
    )
    .iloc[0]
)


print(
    "Borne avec le RMSE théorique "
    "combiné le plus faible :",
    best_clipping_row[
        "upper_bound_kwh"
    ],
    "kWh"
)


display(
    best_clipping_row
)

Borne avec le RMSE théorique combiné le plus faible : 100.0 kWh

upper_bound_kwh           100.000000
clipped_share_percent       0.000000
clipping_bias_kwh           0.000000
dp_theoretical_rmse       141.421356
combined_expected_rmse    141.421356
Name: 4, dtype: float64

In [201]:
# ==========================================
# PRIVACY / UTILITY CURVE
# ==========================================

privacy_utility_df = (
    dp_results_df[
        [
            "epsilon",
            "mae",
            "rmse",
            "relative_mae_percent",
        ]
    ]
    .copy()
)


privacy_utility_df[
    "privacy_noise_scale"
] = (
    COUNT_SENSITIVITY
    / privacy_utility_df[
        "epsilon"
    ]
)


display(
    privacy_utility_df
)

   epsilon        mae       rmse  relative_mae_percent  privacy_noise_scale
0      0.1  10.578911  14.711279              4.231564                 10.0
1      0.5   1.912325   2.681148              0.764930                  2.0
2      1.0   1.068424   1.520733              0.427370                  1.0
3      2.0   0.485590   0.682008              0.194236                  0.5
4      5.0   0.193923   0.271307              0.077569                  0.2
5     10.0   0.106589   0.148069              0.042636                  0.1

In [202]:
# ==========================================
# SAVE STEP 5
# ==========================================

STEP5_PATH = (
    DATA_DIR
    / "block11_user_level_dp.joblib"
)


step5_state = {

    "privacy_enabled":
        PRIVACY_ENABLED,

    "privacy_lab_enabled":
        RUN_PRIVACY_LAB,

    "rows_per_household":
        ROWS_PER_HOUSEHOLD,

    "row_level_sensitivity":
        ROW_LEVEL_SENSITIVITY,

    "user_level_sensitivity":
        USER_LEVEL_SENSITIVITY,

    "total_epsilon_budget":
        TOTAL_EPSILON_BUDGET,

    "composition_results":
        composition_results_df,

    "clipping_results":
        clipping_results_df,

    "privacy_utility":
        privacy_utility_df,

    "uses_2026":
        False,
}


joblib.dump(
    step5_state,
    STEP5_PATH
)


print(
    "Sauvegardé :",
    STEP5_PATH
)

Sauvegardé : C:\Users\thiba\OneDrive\Bureau\Projet energie\data_processed\block11_user_level_dp.joblib

In [203]:
# ==========================================
# STEP 5 PERFORMANCE SUMMARY
# ==========================================

step5_summary = pd.DataFrame({

    "Indicateur": [
        "Rows / household",
        "Row-level sensitivity",
        "User-level sensitivity",
        "Total epsilon budget",
        "Privacy production",
        "Privacy laboratory",
        "2026",
    ],

    "Valeur": [
        ROWS_PER_HOUSEHOLD,
        ROW_LEVEL_SENSITIVITY,
        USER_LEVEL_SENSITIVITY,
        TOTAL_EPSILON_BUDGET,
        "OFF",
        "ON",
        "Untouched",
    ],
})


display(
    step5_summary
)

               Indicateur     Valeur
0        Rows / household         48
1   Row-level sensitivity          1
2  User-level sensitivity         48
3    Total epsilon budget        1.0
4      Privacy production        OFF
5      Privacy laboratory         ON
6                    2026  Untouched

### Partie C — Analyse et améliorations guidées par la théorie

La définition de l'unité de confidentialité est particulièrement
importante pour des séries temporelles individuelles.

Lorsqu'un foyer fournit 48 observations, une protection Row-Level et
une protection User-Level ne correspondent pas au même modèle de
menace.

Pour un comptage réalisé directement sur les lignes :

$$
\Delta_{\text{row}} = 1,
$$

alors qu'un foyer complet peut contribuer jusqu'à :

$$
\Delta_{\text{user}} = 48.
$$

Une agrégation préalable au niveau utilisateur peut cependant réduire
fortement cette sensibilité.

Pour un indicateur binaire calculé une fois par foyer :

$$
Y_i\in\{0,1\},
$$

la sensibilité utilisateur du comptage redevient :

$$
\Delta=1.
$$

La composition constitue un deuxième élément fondamental.

Pour plusieurs mécanismes utilisant respectivement :

$$
\varepsilon_1,\ldots,\varepsilon_m,
$$

la composition séquentielle simple donne :

$$
\varepsilon_{\text{total}}
=
\sum_{j=1}^{m}\varepsilon_j.
$$

Les publications répétées consomment donc progressivement le budget de
confidentialité.

Enfin, le clipping introduit un compromis supplémentaire.

Une borne faible réduit la sensibilité du mécanisme mais peut créer un
biais important.

Une borne élevée conserve davantage d'information mais augmente le
bruit nécessaire à la confidentialité.

Ce compromis peut être représenté par :

$$
RMSE_{total}
=
\sqrt{
Bias_{clip}^2
+
2
\left(
\frac{B}{\varepsilon}
\right)^2
}.
$$

Ces résultats montrent que la confidentialité différentielle nécessite
de choisir conjointement :

- l'unité de confidentialité ;
- la granularité des données ;
- les bornes de contribution ;
- le nombre de publications ;
- le budget epsilon.

Conclusion :

L'Étape 5 montre que la protection au niveau utilisateur peut être
nettement plus exigeante qu'une protection ligne par ligne lorsque
chaque utilisateur possède plusieurs observations.

L'agrégation préalable au niveau foyer permet toutefois de réduire la
sensibilité de certaines statistiques.

La composition montre également qu'un budget de confidentialité ne peut
pas être réutilisé gratuitement pour un nombre arbitraire de requêtes.

Enfin, l'expérience sur le clipping met en évidence un compromis entre
biais statistique et quantité de bruit nécessaire.

Ces mécanismes restent confinés au laboratoire synthétique du Bloc 11.

Le pipeline énergétique principal conserve `Privacy = OFF` et l'année
2026 reste intacte.

## Étape 6 — Modèle de classification et audit d'équité

### Partie A — Mise en pratique

Cette étape entraîne un modèle de classification sur le sandbox
synthétique puis évalue ses performances globalement et séparément
selon le groupe synthétique.

La variable sensible n'est pas utilisée comme variable prédictive.

Elle est uniquement utilisée pour l'audit d'équité.

In [204]:
# ==========================================
# FAIRLEARN CHECK
# ==========================================

try:

    import fairlearn

    print(
        "Fairlearn version :",
        fairlearn.__version__
    )

except ImportError:

    print(
        "Fairlearn n'est pas installé."
    )

Fairlearn version : 0.14.0

In [205]:
# ==========================================
# ML / FAIRNESS IMPORTS
# ==========================================

import time

from functools import partial

from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import (
    OneHotEncoder,
    StandardScaler,
)

from fairlearn.metrics import (
    MetricFrame,
    demographic_parity_difference,
    demographic_parity_ratio,
    equalized_odds_difference,
    false_positive_rate,
    selection_rate,
    true_positive_rate,
)

In [206]:
# ==========================================
# MODEL FEATURES
# ==========================================

FEATURES = [
    "household_size",
    "dwelling_type",
    "electric_heating",
    "energy_efficiency",
]


TARGET = (
    "high_consumption"
)


SENSITIVE_FEATURE = (
    "sensitive_group"
)


X = household_dataset[
    FEATURES
].copy()


y = household_dataset[
    TARGET
].copy()


sensitive = household_dataset[
    SENSITIVE_FEATURE
].copy()


print(
    "X :",
    X.shape
)

print(
    "Classe positive :",
    f"{100 * y.mean():.2f} %"
)

print(
    sensitive.value_counts()
)

X : (1000, 4)
Classe positive : 25.00 %
sensitive_group
A    545
B    455
Name: count, dtype: int64

### Attribut sensible et variables prédictives

La variable :

`sensitive_group`

n'est pas fournie au modèle.

Le modèle utilise uniquement :

- la taille du foyer ;
- le type de logement ;
- le chauffage électrique ;
- l'efficacité énergétique.

L'attribut sensible est conservé séparément afin de mesurer les
performances du modèle pour chaque groupe.

Cependant, retirer directement l'attribut sensible ne garantit pas
automatiquement l'absence d'écarts entre groupes.

Certaines variables prédictives peuvent être distribuées différemment
selon les groupes et agir comme variables indirectement associées à
l'attribut sensible.

In [207]:
# ==========================================
# TRAIN / TEST SPLIT
# ==========================================

stratification = (
    y.astype(str)
    + "_"
    + sensitive.astype(str)
)


(
    X_train,
    X_test,
    y_train,
    y_test,
    sensitive_train,
    sensitive_test,
) = train_test_split(

    X,
    y,
    sensitive,

    test_size=0.25,

    random_state=RANDOM_STATE,

    stratify=stratification,
)

In [208]:
print(
    "Train :",
    len(X_train)
)

print(
    "Test :",
    len(X_test)
)


split_check = pd.DataFrame({

    "Dataset": [
        "Train",
        "Test",
    ],

    "n": [
        len(X_train),
        len(X_test),
    ],

    "Positive rate": [
        y_train.mean(),
        y_test.mean(),
    ],

    "Group B rate": [
        (
            sensitive_train
            == "B"
        ).mean(),

        (
            sensitive_test
            == "B"
        ).mean(),
    ],
})


display(
    split_check
)

Train : 750
Test : 250

  Dataset    n  Positive rate  Group B rate
0   Train  750       0.250667      0.454667
1    Test  250       0.248000      0.456000

In [209]:
# ==========================================
# PREPROCESSING
# ==========================================

NUMERIC_FEATURES = [
    "household_size",
    "electric_heating",
]


CATEGORICAL_FEATURES = [
    "dwelling_type",
    "energy_efficiency",
]


preprocessor = ColumnTransformer(

    transformers=[

        (
            "numeric",
            StandardScaler(),
            NUMERIC_FEATURES,
        ),

        (
            "categorical",
            OneHotEncoder(
                handle_unknown="ignore"
            ),
            CATEGORICAL_FEATURES,
        ),
    ]
)

In [210]:
# ==========================================
# BASELINE CLASSIFIER
# ==========================================

baseline_model = Pipeline([

    (
        "preprocessing",
        preprocessor,
    ),

    (
        "classifier",
        LogisticRegression(
            max_iter=1000,
            random_state=RANDOM_STATE,
        ),
    ),
])

In [211]:
# ==========================================
# TRAIN MODEL
# ==========================================

training_start = (
    time.perf_counter()
)


baseline_model.fit(
    X_train,
    y_train,
)


training_seconds = (
    time.perf_counter()
    - training_start
)


print(
    "Temps entraînement :",
    f"{training_seconds:.3f} s"
)

Temps entraînement : 0.025 s

In [212]:
# ==========================================
# PREDICTIONS
# ==========================================

y_pred = baseline_model.predict(
    X_test
)


y_proba = (
    baseline_model
    .predict_proba(
        X_test
    )[:, 1]
)

In [213]:
# ==========================================
# GLOBAL PERFORMANCE
# ==========================================

accuracy = accuracy_score(
    y_test,
    y_pred,
)


balanced_accuracy = (
    balanced_accuracy_score(
        y_test,
        y_pred,
    )
)


precision = precision_score(
    y_test,
    y_pred,
    zero_division=0,
)


recall = recall_score(
    y_test,
    y_pred,
    zero_division=0,
)


f1 = f1_score(
    y_test,
    y_pred,
    zero_division=0,
)


roc_auc = roc_auc_score(
    y_test,
    y_proba,
)


global_metrics = pd.DataFrame({

    "Metric": [
        "Accuracy",
        "Balanced Accuracy",
        "Precision",
        "Recall",
        "F1",
        "ROC-AUC",
    ],

    "Value": [
        accuracy,
        balanced_accuracy,
        precision,
        recall,
        f1,
        roc_auc,
    ],
})


display(
    global_metrics
)

              Metric     Value
0           Accuracy  0.992000
1  Balanced Accuracy  0.989276
2          Precision  0.983871
3             Recall  0.983871
4                 F1  0.983871
5            ROC-AUC  0.998842

In [214]:
# ==========================================
# CONFUSION MATRIX
# ==========================================

cm = confusion_matrix(
    y_test,
    y_pred,
)


confusion_df = pd.DataFrame(

    cm,

    index=[
        "Actual 0",
        "Actual 1",
    ],

    columns=[
        "Predicted 0",
        "Predicted 1",
    ],
)


display(
    confusion_df
)

          Predicted 0  Predicted 1
Actual 0          187            1
Actual 1            1           61

In [215]:
# ==========================================
# FAIRNESS METRICS
# ==========================================

fairness_metrics = {

    "accuracy":
        accuracy_score,

    "selection_rate":
        selection_rate,

    "true_positive_rate":
        true_positive_rate,

    "false_positive_rate":
        false_positive_rate,

    "precision":
        partial(
            precision_score,
            zero_division=0,
        ),

    "recall":
        partial(
            recall_score,
            zero_division=0,
        ),
}

In [216]:
# ==========================================
# METRIC FRAME
# ==========================================

metric_frame = MetricFrame(

    metrics=fairness_metrics,

    y_true=y_test,

    y_pred=y_pred,

    sensitive_features=sensitive_test,
)

In [217]:
print(
    "Métriques globales :"
)

display(
    pd.Series(
        metric_frame.overall
    )
)


print(
    "\nMétriques par groupe :"
)

display(
    metric_frame.by_group
)

Métriques globales :

accuracy               0.992000
selection_rate         0.248000
true_positive_rate     0.983871
false_positive_rate    0.005319
precision              0.983871
recall                 0.983871
dtype: float64

Métriques par groupe :

,accuracy,selection_rate,true_positive_rate,false_positive_rate,precision,recall
sensitive_group,,,,,,
A,1.000000,0.235294,1.000000,0.000000,1.000000,1.000000
B,0.982456,0.263158,0.966667,0.011905,0.966667,0.966667

In [218]:
# ==========================================
# METRIC DIFFERENCES
# ==========================================

group_differences = (
    metric_frame.difference(
        method="between_groups"
    )
)


display(
    pd.Series(
        group_differences,
        name="Absolute difference",
    )
)

accuracy               0.017544
selection_rate         0.027864
true_positive_rate     0.033333
false_positive_rate    0.011905
precision              0.033333
recall                 0.033333
Name: Absolute difference, dtype: float64

In [219]:
# ==========================================
# DEMOGRAPHIC PARITY
# ==========================================

dp_difference = (
    demographic_parity_difference(

        y_test,
        y_pred,

        sensitive_features=
            sensitive_test,
    )
)


dp_ratio = (
    demographic_parity_ratio(

        y_test,
        y_pred,

        sensitive_features=
            sensitive_test,
    )
)


print(
    "Demographic parity difference :",
    dp_difference
)

print(
    "Demographic parity ratio :",
    dp_ratio
)

Demographic parity difference : 0.02786377708978327
Demographic parity ratio : 0.8941176470588236

In [220]:
# ==========================================
# EQUALIZED ODDS
# ==========================================

eo_difference = (
    equalized_odds_difference(

        y_test,
        y_pred,

        sensitive_features=
            sensitive_test,
    )
)


print(
    "Equalized odds difference :",
    eo_difference
)

Equalized odds difference : 0.033333333333333326

In [221]:
# ==========================================
# FAIRNESS SUMMARY
# ==========================================

fairness_summary = pd.DataFrame({

    "Metric": [
        "Demographic parity difference",
        "Demographic parity ratio",
        "Equalized odds difference",
    ],

    "Value": [
        dp_difference,
        dp_ratio,
        eo_difference,
    ],
})


display(
    fairness_summary
)

                          Metric     Value
0  Demographic parity difference  0.027864
1       Demographic parity ratio  0.894118
2      Equalized odds difference  0.033333

In [222]:
# ==========================================
# ACTUAL VS PREDICTED POSITIVE RATE
# ==========================================

fairness_analysis_df = pd.DataFrame({

    "y_true":
        y_test.to_numpy(),

    "y_pred":
        y_pred,

    "group":
        sensitive_test.to_numpy(),
})


actual_predicted_by_group = (
    fairness_analysis_df
    .groupby(
        "group"
    )
    .agg(

        n=(
            "y_true",
            "size"
        ),

        actual_positive_rate=(
            "y_true",
            "mean"
        ),

        predicted_positive_rate=(
            "y_pred",
            "mean"
        ),
    )
)


display(
    actual_predicted_by_group
)

         n  actual_positive_rate  predicted_positive_rate
group
A      136              0.235294                 0.235294
B      114              0.263158                 0.263158

In [223]:
# ==========================================
# SAVE BASELINE MODEL
# ==========================================

FAIRNESS_MODEL_PATH = (
    MODEL_DIR
    / "block11_fairness_baseline.joblib"
)


joblib.dump(
    baseline_model,
    FAIRNESS_MODEL_PATH
)


print(
    "Modèle sauvegardé :",
    FAIRNESS_MODEL_PATH
)

Modèle sauvegardé : C:\Users\thiba\OneDrive\Bureau\Projet energie\models\block11_fairness_baseline.joblib

In [224]:
# ==========================================
# SAVE FAIRNESS AUDIT
# ==========================================

STEP6_PATH = (
    DATA_DIR
    / "block11_fairness_audit.joblib"
)


step6_state = {

    "global_metrics":
        global_metrics,

    "metrics_by_group":
        metric_frame.by_group,

    "metric_differences":
        group_differences,

    "fairness_summary":
        fairness_summary,

    "actual_predicted_by_group":
        actual_predicted_by_group,

    "training_seconds":
        training_seconds,

    "privacy_enabled":
        PRIVACY_ENABLED,

    "uses_sensitive_attribute_in_model":
        False,

    "uses_2026":
        False,
}


joblib.dump(
    step6_state,
    STEP6_PATH
)


print(
    "Audit sauvegardé :",
    STEP6_PATH
)

Audit sauvegardé : C:\Users\thiba\OneDrive\Bureau\Projet energie\data_processed\block11_fairness_audit.joblib

In [225]:
# ==========================================
# STEP 6 PERFORMANCE SUMMARY
# ==========================================

step6_summary = pd.DataFrame({

    "Indicator": [
        "Accuracy",
        "Balanced accuracy",
        "F1",
        "ROC-AUC",
        "DP difference",
        "DP ratio",
        "EO difference",
        "Sensitive feature used by model",
        "Privacy production",
        "2026",
    ],

    "Value": [
        accuracy,
        balanced_accuracy,
        f1,
        roc_auc,
        dp_difference,
        dp_ratio,
        eo_difference,
        False,
        "OFF",
        "Untouched",
    ],
})


display(
    step6_summary
)

                         Indicator      Value
0                         Accuracy      0.992
1                Balanced accuracy   0.989276
2                               F1   0.983871
3                          ROC-AUC   0.998842
4                    DP difference   0.027864
5                         DP ratio   0.894118
6                    EO difference   0.033333
7  Sensitive feature used by model      False
8               Privacy production        OFF
9                             2026  Untouched

### Partie C — Analyse et améliorations guidées par la théorie

L'audit d'équité doit être séparé de la performance globale du modèle.

Un modèle peut obtenir une bonne accuracy globale tout en présentant des
performances différentes entre groupes.

La Demographic Parity étudie les taux de sélection :

$$
P(\hat Y=1\mid A=a).
$$

La différence de Demographic Parity peut être écrite :

$$
\Delta_{DP}
=
\max_a
P(\hat Y=1\mid A=a)
-
\min_a
P(\hat Y=1\mid A=a).
$$

Une valeur proche de zéro indique des taux de sélection similaires.

L'Equalized Odds étudie plutôt les erreurs conditionnellement à la
véritable classe.

Elle compare notamment :

$$
TPR_a
=
P(\hat Y=1\mid Y=1,A=a)
$$

et :

$$
FPR_a
=
P(\hat Y=1\mid Y=0,A=a).
$$

Ces critères mesurent des propriétés différentes et peuvent mener à
des diagnostics différents.

L'attribut sensible n'est pas fourni au classifieur.

Cependant, cela ne garantit pas que les prédictions soient
indépendantes du groupe, car d'autres variables peuvent être
statistiquement associées à celui-ci.

Enfin, le groupe utilisé ici est entièrement synthétique.

Les résultats constituent donc une démonstration méthodologique et ne
doivent pas être interprétés comme un audit de groupes réels présents
dans les données énergétiques RTE.

Conclusion :

L'Étape 6 ajoute un modèle de classification au sandbox synthétique et
évalue simultanément ses performances prédictives et ses performances
par groupe.

L'attribut sensible est exclu des variables prédictives et n'est
utilisé que pour l'audit.

Fairlearn permet de comparer les métriques globales et désagrégées,
ainsi que plusieurs critères d'équité tels que la Demographic Parity et
l'Equalized Odds.

Ces résultats fourniront la baseline nécessaire pour étudier ensuite
des méthodes de mitigation.

La Privacy du pipeline principal reste désactivée et aucune donnée de
2026 n'est utilisée.

## Étape 7 — Mitigation des écarts entre groupes

### Partie A — Mise en pratique

La baseline obtenue à l'étape précédente présente déjà :

- une très forte performance globale ;
- de faibles écarts entre groupes ;
- une Equalized Odds Difference faible.

L'objectif de cette étape n'est donc pas de forcer artificiellement une
parité parfaite.

On cherche plutôt à étudier le compromis entre :

$$
\text{performance}
$$

et :

$$
\text{fairness}.
$$

La méthode utilisée est Exponentiated Gradient avec une contrainte
d'Equalized Odds.

In [226]:
# ==========================================
# FAIRLEARN MITIGATION IMPORTS
# ==========================================

from fairlearn.reductions import (
    EqualizedOdds,
    ExponentiatedGradient,
)

### Pourquoi utiliser Equalized Odds ?

La baseline présente déjà un écart de Demographic Parity relativement
faible.

Comme les taux réels de classe positive diffèrent légèrement entre les
groupes synthétiques, forcer exactement la même proportion de décisions
positives pourrait modifier artificiellement les prédictions.

On choisit donc plutôt de contrôler les différences de taux d'erreur.

Equalized Odds compare notamment :

$$
TPR_A
\quad\text{et}\quad
TPR_B,
$$

ainsi que :

$$
FPR_A
\quad\text{et}\quad
FPR_B.
$$

Cette contrainte est donc adaptée à l'analyse de la qualité des
prédictions conditionnellement à la véritable classe.

In [227]:
# ==========================================
# FAIRNESS CONSTRAINT GRID
# ==========================================

FAIRNESS_EPS_VALUES = [
    0.001,
    0.01,
    0.02,
    0.05,
]

In [228]:
# ==========================================
# MITIGATION BASE ESTIMATOR
# ==========================================

mitigation_pipeline = Pipeline([

    (
        "preprocessing",
        preprocessor,
    ),

    (
        "classifier",
        LogisticRegression(
            max_iter=1000,
            random_state=RANDOM_STATE,
        ),
    ),
])

In [229]:
# ==========================================
# TRAIN MITIGATED MODELS
# ==========================================

mitigation_results = []

mitigation_models = {}


for fairness_eps in FAIRNESS_EPS_VALUES:

    constraint = EqualizedOdds(
        difference_bound=
            fairness_eps
    )


    mitigated_model = (
        ExponentiatedGradient(

            estimator=
                mitigation_pipeline,

            constraints=
                constraint,

            sample_weight_name=
                "classifier__sample_weight",

            eps=
                fairness_eps,

            max_iter=
                50,
        )
    )


    start_time = (
        time.perf_counter()
    )


    mitigated_model.fit(

        X_train,

        y_train,

        sensitive_features=
            sensitive_train,
    )


    train_time = (
        time.perf_counter()
        - start_time
    )


    y_pred_mitigated = (
        mitigated_model.predict(
            X_test,
            random_state=
                RANDOM_STATE,
        )
    )


    mitigated_accuracy = (
        accuracy_score(
            y_test,
            y_pred_mitigated,
        )
    )


    mitigated_balanced_accuracy = (
        balanced_accuracy_score(
            y_test,
            y_pred_mitigated,
        )
    )


    mitigated_f1 = (
        f1_score(
            y_test,
            y_pred_mitigated,
            zero_division=0,
        )
    )


    mitigated_dp_difference = (
        demographic_parity_difference(

            y_test,

            y_pred_mitigated,

            sensitive_features=
                sensitive_test,
        )
    )


    mitigated_eo_difference = (
        equalized_odds_difference(

            y_test,

            y_pred_mitigated,

            sensitive_features=
                sensitive_test,
        )
    )


    mitigation_results.append({

        "fairness_epsilon":
            fairness_eps,

        "accuracy":
            mitigated_accuracy,

        "balanced_accuracy":
            mitigated_balanced_accuracy,

        "f1":
            mitigated_f1,

        "dp_difference":
            mitigated_dp_difference,

        "eo_difference":
            mitigated_eo_difference,

        "training_seconds":
            train_time,
    })


    mitigation_models[
        fairness_eps
    ] = mitigated_model

In [230]:
mitigation_results_df = (
    pd.DataFrame(
        mitigation_results
    )
)


display(
    mitigation_results_df
)

,fairness_epsilon,accuracy,balanced_accuracy,f1,dp_difference,eo_difference,training_seconds
0,0.001,0.988,0.981211,0.975610,0.019092,0.066667,0.973823
1,0.010,0.992,0.989276,0.983871,0.027864,0.033333,1.119744
2,0.020,0.992,0.989276,0.983871,0.027864,0.033333,0.997262
3,0.050,0.992,0.989276,0.983871,0.027864,0.033333,1.058541

In [231]:
baseline_row = pd.DataFrame({

    "fairness_epsilon": [
        np.nan
    ],

    "accuracy": [
        accuracy
    ],

    "balanced_accuracy": [
        balanced_accuracy
    ],

    "f1": [
        f1
    ],

    "dp_difference": [
        dp_difference
    ],

    "eo_difference": [
        eo_difference
    ],

    "training_seconds": [
        training_seconds
    ],
})

In [232]:
fairness_comparison_df = pd.concat(

    [
        baseline_row.assign(
            model="Baseline"
        ),

        mitigation_results_df.assign(
            model="ExponentiatedGradient"
        ),
    ],

    ignore_index=True,
)


display(
    fairness_comparison_df
)

,fairness_epsilon,accuracy,balanced_accuracy,f1,dp_difference,eo_difference,training_seconds,model
0,NaN,0.992,0.989276,0.983871,0.027864,0.033333,0.024925,Baseline
1,0.001,0.988,0.981211,0.975610,0.019092,0.066667,0.973823,ExponentiatedGradient
2,0.010,0.992,0.989276,0.983871,0.027864,0.033333,1.119744,ExponentiatedGradient
3,0.020,0.992,0.989276,0.983871,0.027864,0.033333,0.997262,ExponentiatedGradient
4,0.050,0.992,0.989276,0.983871,0.027864,0.033333,1.058541,ExponentiatedGradient

In [233]:
# ==========================================
# PERFORMANCE / FAIRNESS DELTAS
# ==========================================

mitigation_results_df[
    "accuracy_change"
] = (
    mitigation_results_df[
        "accuracy"
    ]
    - accuracy
)


mitigation_results_df[
    "balanced_accuracy_change"
] = (
    mitigation_results_df[
        "balanced_accuracy"
    ]
    - balanced_accuracy
)


mitigation_results_df[
    "eo_improvement"
] = (
    eo_difference
    - mitigation_results_df[
        "eo_difference"
    ]
)


display(
    mitigation_results_df
)

,fairness_epsilon,accuracy,balanced_accuracy,f1,dp_difference,eo_difference,training_seconds,accuracy_change,balanced_accuracy_change,eo_improvement
0,0.001,0.988,0.981211,0.975610,0.019092,0.066667,0.973823,-0.004,-0.008065,-0.033333
1,0.010,0.992,0.989276,0.983871,0.027864,0.033333,1.119744,0.000,0.000000,0.000000
2,0.020,0.992,0.989276,0.983871,0.027864,0.033333,0.997262,0.000,0.000000,0.000000
3,0.050,0.992,0.989276,0.983871,0.027864,0.033333,1.058541,0.000,0.000000,0.000000

In [234]:
tradeoff_df = (
    mitigation_results_df[
        [
            "fairness_epsilon",
            "accuracy",
            "balanced_accuracy",
            "f1",
            "eo_difference",
            "dp_difference",
            "accuracy_change",
            "eo_improvement",
        ]
    ]
    .copy()
)


display(
    tradeoff_df
)

,fairness_epsilon,accuracy,balanced_accuracy,f1,eo_difference,dp_difference,accuracy_change,eo_improvement
0,0.001,0.988,0.981211,0.975610,0.066667,0.019092,-0.004,-0.033333
1,0.010,0.992,0.989276,0.983871,0.033333,0.027864,0.000,0.000000
2,0.020,0.992,0.989276,0.983871,0.033333,0.027864,0.000,0.000000
3,0.050,0.992,0.989276,0.983871,0.033333,0.027864,0.000,0.000000

In [235]:
INSPECTION_EPS = 0.02

inspection_model = (
    mitigation_models[
        INSPECTION_EPS
    ]
)


y_pred_inspection = (
    inspection_model.predict(
        X_test,
        random_state=
            RANDOM_STATE,
    )
)

In [236]:
mitigated_metric_frame = MetricFrame(

    metrics=
        fairness_metrics,

    y_true=
        y_test,

    y_pred=
        y_pred_inspection,

    sensitive_features=
        sensitive_test,
)


display(
    mitigated_metric_frame.by_group
)

,accuracy,selection_rate,true_positive_rate,false_positive_rate,precision,recall
sensitive_group,,,,,,
A,1.000000,0.235294,1.000000,0.000000,1.000000,1.000000
B,0.982456,0.263158,0.966667,0.011905,0.966667,0.966667

In [237]:
baseline_group_metrics = (
    metric_frame.by_group
    .copy()
)


mitigated_group_metrics = (
    mitigated_metric_frame.by_group
    .copy()
)


baseline_group_metrics[
    "model"
] = "Baseline"


mitigated_group_metrics[
    "model"
] = "Mitigated"


group_comparison = pd.concat(

    [
        baseline_group_metrics
        .reset_index(),

        mitigated_group_metrics
        .reset_index(),
    ],

    ignore_index=True,
)


display(
    group_comparison
)

,sensitive_group,accuracy,selection_rate,true_positive_rate,false_positive_rate,precision,recall,model
0,A,1.000000,0.235294,1.000000,0.000000,1.000000,1.000000,Baseline
1,B,0.982456,0.263158,0.966667,0.011905,0.966667,0.966667,Baseline
2,A,1.000000,0.235294,1.000000,0.000000,1.000000,1.000000,Mitigated
3,B,0.982456,0.263158,0.966667,0.011905,0.966667,0.966667,Mitigated

In [238]:
# ==========================================
# SAVE MITIGATION MODELS
# ==========================================

MITIGATION_MODEL_PATH = (
    MODEL_DIR
    / "block11_fairness_mitigation.joblib"
)


joblib.dump(

    {
        "models":
            mitigation_models,

        "inspection_epsilon":
            INSPECTION_EPS,

        "baseline_model":
            baseline_model,
    },

    MITIGATION_MODEL_PATH,
)


print(
    "Modèles sauvegardés :",
    MITIGATION_MODEL_PATH
)

Modèles sauvegardés : C:\Users\thiba\OneDrive\Bureau\Projet energie\models\block11_fairness_mitigation.joblib

In [239]:
# ==========================================
# SAVE STEP 7
# ==========================================

STEP7_PATH = (
    DATA_DIR
    / "block11_fairness_mitigation_results.joblib"
)


step7_state = {

    "baseline_accuracy":
        accuracy,

    "baseline_balanced_accuracy":
        balanced_accuracy,

    "baseline_f1":
        f1,

    "baseline_dp_difference":
        dp_difference,

    "baseline_eo_difference":
        eo_difference,

    "mitigation_results":
        mitigation_results_df,

    "tradeoff":
        tradeoff_df,

    "group_comparison":
        group_comparison,

    "privacy_enabled":
        PRIVACY_ENABLED,

    "uses_2026":
        False,
}


joblib.dump(
    step7_state,
    STEP7_PATH
)


print(
    "Sauvegardé :",
    STEP7_PATH
)

Sauvegardé : C:\Users\thiba\OneDrive\Bureau\Projet energie\data_processed\block11_fairness_mitigation_results.joblib

In [240]:
# ==========================================
# STEP 7 PERFORMANCE SUMMARY
# ==========================================

step7_summary = pd.DataFrame({

    "Indicator": [
        "Baseline accuracy",
        "Baseline balanced accuracy",
        "Baseline F1",
        "Baseline DP difference",
        "Baseline EO difference",
        "Mitigation methods tested",
        "Sensitive feature at inference",
        "Privacy production",
        "2026",
    ],

    "Value": [
        accuracy,
        balanced_accuracy,
        f1,
        dp_difference,
        eo_difference,
        len(
            FAIRNESS_EPS_VALUES
        ),
        False,
        "OFF",
        "Untouched",
    ],
})


display(
    step7_summary
)

                        Indicator      Value
0               Baseline accuracy      0.992
1      Baseline balanced accuracy   0.989276
2                     Baseline F1   0.983871
3          Baseline DP difference   0.027864
4          Baseline EO difference   0.033333
5       Mitigation methods tested          4
6  Sensitive feature at inference      False
7              Privacy production        OFF
8                            2026  Untouched

### Partie C — Analyse et améliorations guidées par la théorie

Le modèle baseline présente déjà une très forte performance et des
écarts faibles entre groupes.

La mitigation est donc étudiée comme un compromis et non comme une
correction automatiquement nécessaire.

Exponentiated Gradient transforme le problème de classification sous
contrainte d'équité en une suite de problèmes de classification
pondérés.

La contrainte utilisée ici est Equalized Odds.

Elle cherche à réduire les écarts de :

$$
TPR
$$

et :

$$
FPR
$$

entre groupes.

Une contrainte plus stricte peut réduire les disparités, mais elle peut
également diminuer la performance prédictive.

On étudie donc simultanément :

$$
\Delta Accuracy
$$

et :

$$
\Delta EO.
$$

Le but n'est pas de maximiser une métrique unique, mais d'identifier le
compromis entre précision et contrainte d'équité.

Dans ce sandbox, l'attribut sensible est utilisé uniquement pendant
l'entraînement de la méthode de mitigation.

Le modèle mitigé peut ensuite produire des prédictions sans recevoir
directement cet attribut sensible au moment de l'inférence.

Conclusion :

L'Étape 7 compare la baseline à plusieurs modèles entraînés sous
contrainte d'Equalized Odds.

Cette comparaison permet d'observer si une réduction supplémentaire
des écarts entre groupes justifie ou non la perte éventuelle de
performance prédictive.

Dans notre cas, la baseline possède déjà des écarts relativement
faibles, ce qui rend particulièrement importante l'analyse du compromis
plutôt que l'application automatique d'une mitigation.

Les groupes restent entièrement synthétiques, la Privacy du pipeline
principal reste désactivée et aucune donnée de 2026 n'est utilisée.

## Étape 8 — Configuration finale Privacy × Fairness

### Partie A — Mise en pratique

Les expériences précédentes montrent que la baseline possède déjà :

- une accuracy très élevée ;
- une faible différence de Demographic Parity ;
- une faible différence d'Equalized Odds.

La contrainte la plus stricte testée réduit légèrement la différence de
Demographic Parity, mais augmente la différence d'Equalized Odds et
réduit les performances prédictives.

Les autres configurations testées produisent les mêmes prédictions que
la baseline sur le jeu de test.

La mitigation n'est donc pas retenue dans la configuration finale de ce
sandbox.

La baseline reste le modèle de référence pour l'audit d'équité.

In [241]:
# ==========================================
# BLOCK 11 FINAL CONFIGURATION
# ==========================================

FINAL_PRIVACY_ENABLED = False

FINAL_FAIRNESS_MONITORING = True

FINAL_FAIRNESS_MITIGATION = False

FINAL_MODEL_NAME = (
    "Logistic Regression — Fairness Baseline"
)


final_block11_config = {

    "privacy_enabled":
        FINAL_PRIVACY_ENABLED,

    "privacy_lab_enabled":
        RUN_PRIVACY_LAB,

    "fairness_monitoring":
        FINAL_FAIRNESS_MONITORING,

    "fairness_mitigation":
        FINAL_FAIRNESS_MITIGATION,

    "selected_model":
        FINAL_MODEL_NAME,

    "synthetic_sandbox":
        True,

    "uses_sensitive_feature_for_prediction":
        False,

    "uses_2026":
        False,
}


display(
    pd.Series(
        final_block11_config,
        name="Final Block 11 configuration",
    )
)

privacy_enabled                                                            False
privacy_lab_enabled                                                         True
fairness_monitoring                                                         True
fairness_mitigation                                                        False
selected_model                           Logistic Regression — Fairness Baseline
synthetic_sandbox                                                           True
uses_sensitive_feature_for_prediction                                      False
uses_2026                                                                  False
Name: Final Block 11 configuration, dtype: object

In [242]:
# ==========================================
# PRIVACY ON / OFF COMPARISON
# ==========================================

privacy_comparison = pd.DataFrame({

    "Configuration": [
        "Privacy OFF",
        "Privacy ON — experimental",
    ],

    "Pipeline": [
        "Public energy pipeline",
        "Synthetic privacy lab",
    ],

    "Noise added": [
        "No",
        "Yes",
    ],

    "Data utility": [
        "Original",
        "Reduced depending on epsilon",
    ],

    "Individual DP guarantee": [
        "No",
        "Yes, for calibrated queries",
    ],

    "Selected for production": [
        True,
        False,
    ],
})


display(
    privacy_comparison
)

,Configuration,Pipeline,Noise added,Data utility,Individual DP guarantee,Selected for production
0,Privacy OFF,Public energy pipeline,No,Original,No,True
1,Privacy ON — experimental,Synthetic privacy lab,Yes,Reduced depending on epsilon,"Yes, for calibrated queries",False

In [243]:
# ==========================================
# ANONYMIZATION FINAL RESULTS
# ==========================================

anonymization_final = pd.DataFrame({

    "Metric": [
        "Initial k",
        "Generalized k",
        "Target k",
        "Final k",
        "Suppression rate (%)",
    ],

    "Value": [
        k_initial,
        k_generalized,
        TARGET_K,
        final_k,
        suppression_rate,
    ],
})


display(
    anonymization_final
)

                 Metric  Value
0             Initial k    4.0
1         Generalized k    9.0
2              Target k    5.0
3               Final k    9.0
4  Suppression rate (%)    0.0

In [244]:
# ==========================================
# DIFFERENTIAL PRIVACY FINAL RESULTS
# ==========================================

dp_final_summary = (
    dp_results_df[
        [
            "epsilon",
            "mae",
            "rmse",
            "theoretical_rmse",
            "relative_mae_percent",
        ]
    ]
    .copy()
)


display(
    dp_final_summary
)

   epsilon        mae       rmse  theoretical_rmse  relative_mae_percent
0      0.1  10.578911  14.711279         14.142136              4.231564
1      0.5   1.912325   2.681148          2.828427              0.764930
2      1.0   1.068424   1.520733          1.414214              0.427370
3      2.0   0.485590   0.682008          0.707107              0.194236
4      5.0   0.193923   0.271307          0.282843              0.077569
5     10.0   0.106589   0.148069          0.141421              0.042636

In [245]:
# ==========================================
# COMPOSITION FINAL RESULTS
# ==========================================

composition_final = (
    composition_results_df.copy()
)


composition_final[
    "rmse_gap"
] = (
    composition_final[
        "empirical_rmse"
    ]
    - composition_final[
        "theoretical_rmse"
    ]
)


display(
    composition_final
)

   n_queries  epsilon_per_query  empirical_rmse  theoretical_rmse  rmse_gap
0          1               1.00        1.403295          1.414214 -0.010919
1          2               0.50        2.088794          2.000000  0.088794
2          5               0.20        3.093634          3.162278 -0.068643
3         10               0.10        4.399046          4.472136 -0.073090
4         20               0.05        6.329944          6.324555  0.005388

In [246]:
# ==========================================
# CLIPPING FINAL RESULTS
# ==========================================

clipping_final = (
    clipping_results_df.copy()
)


display(
    clipping_final
)

,upper_bound_kwh,clipped_share_percent,clipping_bias_kwh,dp_theoretical_rmse,combined_expected_rmse
0,50.0,63.7,-10393.014167,70.710678,10393.254710
1,60.0,38.9,-5102.626484,84.852814,5103.331954
2,70.0,21.9,-1995.982203,98.994949,1998.435627
3,80.0,9.6,-559.649640,113.137085,570.970857
4,100.0,0.0,0.000000,141.421356,141.421356

In [247]:
best_bound_row = (
    clipping_final
    .sort_values(
        "combined_expected_rmse"
    )
    .iloc[0]
)


BEST_CLIPPING_BOUND = float(
    best_bound_row[
        "upper_bound_kwh"
    ]
)


print(
    "Meilleure borne parmi celles testées :",
    BEST_CLIPPING_BOUND,
    "kWh"
)

Meilleure borne parmi celles testées : 100.0 kWh

In [248]:
# ==========================================
# FAIRNESS FINAL RESULTS
# ==========================================

fairness_final = pd.DataFrame({

    "Metric": [
        "Accuracy",
        "Balanced Accuracy",
        "Precision",
        "Recall",
        "F1",
        "ROC-AUC",
        "DP difference",
        "DP ratio",
        "EO difference",
    ],

    "Value": [
        accuracy,
        balanced_accuracy,
        precision,
        recall,
        f1,
        roc_auc,
        dp_difference,
        dp_ratio,
        eo_difference,
    ],
})


display(
    fairness_final
)

              Metric     Value
0           Accuracy  0.992000
1  Balanced Accuracy  0.989276
2          Precision  0.983871
3             Recall  0.983871
4                 F1  0.983871
5            ROC-AUC  0.998842
6      DP difference  0.027864
7           DP ratio  0.894118
8      EO difference  0.033333

In [249]:
# ==========================================
# MITIGATION FINAL DECISION
# ==========================================

mitigation_decision = pd.DataFrame({

    "Model": [
        "Baseline",
        "Strict mitigation",
    ],

    "Accuracy": [
        accuracy,
        0.988,
    ],

    "DP difference": [
        dp_difference,
        0.019092,
    ],

    "EO difference": [
        eo_difference,
        0.066667,
    ],
})


display(
    mitigation_decision
)

               Model  Accuracy  DP difference  EO difference
0           Baseline     0.992       0.027864       0.033333
1  Strict mitigation     0.988       0.019092       0.066667

In [250]:
print(
    "Configuration retenue :",
    FINAL_MODEL_NAME
)

Configuration retenue : Logistic Regression — Fairness Baseline

In [251]:
# ==========================================
# BLOCK 11 VALIDATION
# ==========================================

assert len(
    household_dataset
) == 1000


assert len(
    microdata
) == 48000


assert (
    final_k
    >= TARGET_K
)


assert (
    suppression_rate
    >= 0
)


assert (
    suppression_rate
    <= 100
)


assert (
    accuracy
    >= 0
    and accuracy
    <= 1
)


assert (
    dp_difference
    >= 0
)


assert (
    eo_difference
    >= 0
)


assert (
    FINAL_PRIVACY_ENABLED
    is False
)


assert (
    final_block11_config[
        "uses_2026"
    ]
    is False
)


print(
    "Bloc 11 validation : OK"
)

Bloc 11 validation : OK

In [252]:
# ==========================================
# SAVE BLOCK 11 FINAL STATE
# ==========================================

BLOCK11_FINAL_PATH = (
    MODEL_DIR
    / "block11_final_state.joblib"
)


block11_final_state = {

    "configuration":
        final_block11_config,

    "anonymization":
        anonymization_final,

    "differential_privacy":
        dp_final_summary,

    "composition":
        composition_final,

    "clipping":
        clipping_final,

    "fairness":
        fairness_final,

    "mitigation_results":
        mitigation_results_df,

    "selected_fairness_model":
        baseline_model,

    "privacy_enabled":
        False,

    "uses_2026":
        False,

    "random_state":
        RANDOM_STATE,
}


joblib.dump(
    block11_final_state,
    BLOCK11_FINAL_PATH
)


print(
    "État final sauvegardé :",
    BLOCK11_FINAL_PATH
)

print(
    "Existe :",
    BLOCK11_FINAL_PATH.exists()
)

État final sauvegardé : C:\Users\thiba\OneDrive\Bureau\Projet energie\models\block11_final_state.joblib
Existe : True

In [253]:
# ==========================================
# RELOAD FINAL STATE
# ==========================================

loaded_block11 = joblib.load(
    BLOCK11_FINAL_PATH
)


print(
    "Privacy :",
    loaded_block11[
        "privacy_enabled"
    ]
)

print(
    "2026 utilisé :",
    loaded_block11[
        "uses_2026"
    ]
)

print(
    "Modèle :",
    loaded_block11[
        "configuration"
    ][
        "selected_model"
    ]
)

Privacy : False
2026 utilisé : False
Modèle : Logistic Regression — Fairness Baseline

## Performance Summary — Bloc 11

Le Bloc 11 étudie la confidentialité, l'anonymisation et l'équité
algorithmique dans un environnement synthétique séparé du pipeline
énergétique principal.

### Configuration

Le pipeline principal utilise des données énergétiques publiques et
agrégées.

La configuration retenue est donc :

$$
\boxed{Privacy_{production}=OFF}.
$$

Les expériences de confidentialité restent activées uniquement dans un
laboratoire synthétique.

### Sandbox

Le sandbox contient :

$$
1000
$$

foyers et :

$$
48
$$

observations temporelles par foyer, soit :

$$
48\,000
$$

micro-observations.

### k-anonymité

Le niveau initial est :

$$
k=4.
$$

Après généralisation :

$$
k=9.
$$

La cible :

$$
k\geq5
$$

est donc satisfaite sans supprimer d'observation :

$$
Suppression=0\%.
$$

### Differential Privacy

Le mécanisme de Laplace est étudié pour plusieurs valeurs du budget :

$$
\varepsilon
\in
\{0.1,0.5,1,2,5,10\}.
$$

Pour un comptage de sensibilité :

$$
\Delta f=1,
$$

le RMSE théorique est :

$$
RMSE=
\frac{\sqrt{2}}{\varepsilon}.
$$

Les simulations Monte-Carlo reproduisent correctement cette relation.

Pour :

$$
\varepsilon=1,
$$

le RMSE empirique obtenu est approximativement :

$$
1.521,
$$

contre :

$$
1.414
$$

théoriquement.

### Composition

À budget total fixé :

$$
\varepsilon_{total}=1,
$$

le RMSE augmente avec le nombre de publications.

Pour 20 requêtes :

$$
RMSE_{emp}=6.330
$$

contre :

$$
RMSE_{th}=6.325.
$$

### Clipping

Le clipping montre le compromis entre biais et bruit.

Parmi les bornes étudiées, la borne :

$$
B=100\text{ kWh}
$$

donne le RMSE combiné théorique le plus faible.

### Fairness

Le classifieur baseline atteint :

$$
Accuracy=0.992,
$$

$$
BalancedAccuracy=0.9893,
$$

$$
F1=0.9839,
$$

et :

$$
ROC\text{-}AUC=0.9988.
$$

Les écarts observés sont :

$$
DP_{difference}=0.0279,
$$

$$
DP_{ratio}=0.8941,
$$

et :

$$
EO_{difference}=0.0333.
$$

### Mitigation

Une mitigation par Exponentiated Gradient sous contrainte d'Equalized
Odds a été testée.

La contrainte la plus stricte réduit la différence de Demographic
Parity, mais diminue les performances prédictives et augmente la
différence d'Equalized Odds.

Les autres configurations testées donnent les mêmes résultats que la
baseline.

La baseline est donc conservée pour l'état final du Bloc 11.

### Test final

L'année 2026 reste totalement exclue de ces analyses.

### Conclusion

Le Bloc 11 montre que les mécanismes de confidentialité et d'équité ne
doivent pas être appliqués automatiquement.

La confidentialité différentielle a été étudiée dans un environnement
synthétique afin de comprendre l'effet du budget epsilon, de la
sensibilité, du clipping et de la composition.

Elle n'est pas activée dans le pipeline énergétique principal, car les
données exploitées sont publiques et agrégées.

L'audit d'équité montre que la baseline possède déjà de faibles écarts
entre les groupes synthétiques.

Les méthodes de mitigation testées n'apportent pas d'amélioration
simultanée claire des performances et de l'Equalized Odds.

Le système final conserve donc la baseline et maintient un mécanisme
d'audit d'équité plutôt qu'une mitigation systématique.

Aucune information de l'année 2026 n'a été utilisée.